import type { LocalizedStartCopyBundle, StartFormCopy, StartPageCopy } from './start-copy'

const ENGLISH_HOME_HREF = 'https://happydoctor.kr/en'

type LocalizedStartCopyInput = {
  page: Omit<StartPageCopy, 'homeHref'>
  form: Omit<StartFormCopy, 'genderOptions'>
  genderOptionLabels: [string, string, string, string]
}

function createBundle({
  page,
  form,
  genderOptionLabels,
}: LocalizedStartCopyInput): LocalizedStartCopyBundle {
  return {
    page: {
      ...page,
      homeHref: ENGLISH_HOME_HREF,
    },
    form: {
      ...form,
      genderOptions: [
        { value: 'female', label: genderOptionLabels[0] },
        { value: 'male', label: genderOptionLabels[1] },
        { value: 'other', label: genderOptionLabels[2] },
        { value: 'prefer_not_to_say', label: genderOptionLabels[3] },
      ],
    },
  }
}

export const localizedStartCopyByInputLanguage: Record<string, LocalizedStartCopyBundle> = {
  es: createBundle({
    page: {
      eyebrow: 'Inicio de Happy Doctor',
      title: 'Inicia una consulta en la web',
      description: 'Comparte solo la información esencial y abriremos tu consulta con un enlace de estado y un código de búsqueda.',
      homeLabel: 'Página principal en inglés',
      statusLabel: 'Verificar estado',
      heroEyebrow: 'Acceso a la atención',
      heroTitle: 'Un lugar para explicar primero\ncuando la atención médica se siente lejana',
      heroBody: 'Esta página es una puerta de entrada a apoyo médico en línea para personas que necesitan explicar lo que está pasando antes de saber dónde pedir ayuda.',
      infoTitle: 'Cuéntanos',
      infoItems: [
        'qué es lo que más te incomoda ahora',
        'cuándo empezó',
        'si tienes enfermedades crónicas o tomas medicamentos',
      ],
      supportEyebrow: 'Cómo funciona',
      supportTitle: 'Escríbenos en tu idioma',
      supportItems: [
        'Si tus síntomas parecen urgentes, usa primero los servicios de emergencia.',
        'Puedes escribir en el idioma que elegiste para esta página.',
        'Intentaremos traducir tu mensaje automáticamente para nuestros médicos.',
      ],
    },
    form: {
      recentEyebrow: 'Consulta reciente',
      recentBody: 'Tu consulta más reciente estará disponible durante una hora.\nPuedes continuar con el código {code}.',
      recentLink: 'Continuar consulta reciente',
      restoredDraft: 'Restauramos lo que estabas escribiendo para que puedas continuar y enviar la consulta.',
      languageHintEyebrow: 'Soporte de idioma',
      languageHintTitle: 'Puedes escribir en {language}.',
      languageHintBody: 'Intentaremos detectar automáticamente el texto en {language}, traducirlo al coreano para nuestros médicos y devolver una respuesta traducida en el mismo idioma cuando sea posible.',
      phoneConsentRequired: 'Ingresa un número de teléfono si quieres recibir alertas de respuesta.',
      phoneConsentMismatch: 'Solo guardamos un contacto para alertas de respuesta cuando aceptas recibirlas.',
      submitError: 'No pudimos iniciar la consulta en este momento. Inténtalo de nuevo en unos minutos.',
      ageLabel: 'Edad o rango de edad',
      agePlaceholder: 'Ejemplo: 40 años, 27 años',
      genderLabel: 'Género',
      genderPlaceholder: 'Prefiero no decirlo',
      chiefComplaintLabel: 'Síntoma principal',
      chiefComplaintPlaceholder: 'Ejemplo: dolor de estómago, tos, fiebre',
      onsetLabel: '¿Cuándo empezó?',
      onsetPlaceholder: 'Ejemplo: esta mañana, hace 3 días',
      nrsLabel: 'Puntuación de dolor o síntomas',
      nrsUnknown: 'No estoy seguro',
      symptomDetailLabel: 'Cuéntanos más',
      symptomDetailPlaceholder: 'Describe qué te incomoda y qué es lo que más te preocupa ahora mismo.',
      associatedLabel: 'Otros síntomas',
      associatedPlaceholder: 'Ejemplo: vómitos, fiebre, diarrea, tos',
      historyLabel: 'Antecedentes médicos o medicamentos',
      historyPlaceholder: 'Cuéntanos si tienes enfermedades crónicas o si tomas medicamentos.',
      imageLabel: 'Agregar fotos',
      imageDescription: 'Si tienes fotos de un sarpullido, una herida o un envase de medicamento, pueden ayudarnos a entender mejor tu situación.\nPuedes subir hasta 3 imágenes, de hasta 10 MB cada una.',
      imageChooseLabel: 'Elegir archivos',
      imageEmptyLabel: 'No se seleccionó ningún archivo',
      imageSelectedLabel: '{count} archivos seleccionados',
      notificationTitle: 'Deja un número para alertas de respuesta',
      notificationDescription: 'Opcional. Solo usamos este contacto si aceptas recibir una alerta cuando haya una respuesta.',
      phoneLabel: 'Número de teléfono',
      phonePlaceholder: 'Ejemplo: +82 10-1234-5678',
      policyNote: 'Si sientes que es una urgencia, usa primero los servicios de emergencia. Happy Doctor no reemplaza la atención de urgencias. Es un servicio de apoyo en línea para personas que necesitan pedir ayuda antes de que la atención médica sea aún más difícil de alcanzar.',
      submitLoading: 'Bodeum está organizando tu consulta...',
      submitIdle: 'Iniciar consulta en la web',
      englishSupportNote: 'Esta página ya está traducida al idioma que elegiste. Algunas respuestas posteriores pueden requerir aclaraciones sobre matices médicos.',
    },
    genderOptionLabels: ['Mujer', 'Hombre', 'Otro', 'Prefiero no decirlo'],
  }),
  vi: createBundle({
    page: {
      eyebrow: 'Bắt đầu cùng Happy Doctor',
      title: 'Bắt đầu tư vấn trên web',
      description: 'Chỉ cần chia sẻ những thông tin cần thiết và chúng tôi sẽ mở cuộc tư vấn với liên kết trạng thái và mã tra cứu.',
      homeLabel: 'Trang chủ tiếng Anh',
      statusLabel: 'Kiểm tra trạng thái',
      heroEyebrow: 'Cửa vào chăm sóc',
      heroTitle: 'Một nơi để giải thích trước\nkhi việc tiếp cận y tế trở nên xa vời',
      heroBody: 'Trang này là điểm bắt đầu hỗ trợ y tế trực tuyến cho những người cần giải thích tình trạng của mình trước khi biết nên tìm sự giúp đỡ ở đâu.',
      infoTitle: 'Hãy cho chúng tôi biết',
      infoItems: [
        'điều gì đang khiến bạn khó chịu nhất lúc này',
        'bắt đầu từ khi nào',
        'bạn có bệnh mạn tính hay đang dùng thuốc gì không',
      ],
      supportEyebrow: 'Cách hoạt động',
      supportTitle: 'Hãy viết bằng ngôn ngữ của bạn',
      supportItems: [
        'Nếu triệu chứng có vẻ khẩn cấp, vui lòng liên hệ cấp cứu trước.',
        'Bạn có thể viết bằng ngôn ngữ đã chọn cho trang này.',
        'Chúng tôi sẽ cố gắng tự động dịch tin nhắn của bạn cho bác sĩ.',
      ],
    },
    form: {
      recentEyebrow: 'Tư vấn gần đây',
      recentBody: 'Cuộc tư vấn gần nhất của bạn sẽ còn hiển thị trong một giờ.\nBạn có thể tiếp tục với mã {code}.',
      recentLink: 'Tiếp tục cuộc tư vấn gần đây',
      restoredDraft: 'Chúng tôi đã khôi phục nội dung bạn đang nhập để bạn có thể tiếp tục và gửi yêu cầu tư vấn.',
      languageHintEyebrow: 'Hỗ trợ ngôn ngữ',
      languageHintTitle: 'Bạn có thể viết bằng {language}.',
      languageHintBody: 'Chúng tôi sẽ cố gắng tự động nhận diện nội dung {language}, dịch sang tiếng Hàn cho bác sĩ và gửi lại phản hồi bằng cùng ngôn ngữ nếu có thể.',
      phoneConsentRequired: 'Vui lòng nhập số điện thoại nếu bạn muốn nhận thông báo phản hồi.',
      phoneConsentMismatch: 'Chúng tôi chỉ lưu số liên hệ nhận thông báo khi bạn đồng ý nhận thông báo phản hồi.',
      submitError: 'Hiện chưa thể bắt đầu tư vấn. Vui lòng thử lại sau ít phút.',
      ageLabel: 'Tuổi hoặc nhóm tuổi',
      agePlaceholder: 'Ví dụ: khoảng 40 tuổi, 27 tuổi',
      genderLabel: 'Giới tính',
      genderPlaceholder: 'Không muốn trả lời',
      chiefComplaintLabel: 'Triệu chứng chính',
      chiefComplaintPlaceholder: 'Ví dụ: đau bụng, ho, sốt',
      onsetLabel: 'Bắt đầu từ khi nào?',
      onsetPlaceholder: 'Ví dụ: sáng nay, 3 ngày trước',
      nrsLabel: 'Mức độ đau hoặc triệu chứng',
      nrsUnknown: 'Không chắc',
      symptomDetailLabel: 'Hãy kể chi tiết hơn',
      symptomDetailPlaceholder: 'Hãy mô tả điều gì khiến bạn khó chịu và điều gì làm bạn lo lắng nhất lúc này.',
      associatedLabel: 'Các triệu chứng khác',
      associatedPlaceholder: 'Ví dụ: nôn, sốt, tiêu chảy, ho',
      historyLabel: 'Bệnh nền hoặc thuốc đang dùng',
      historyPlaceholder: 'Nếu có bệnh mạn tính hoặc thuốc đang dùng, vui lòng ghi giúp chúng tôi.',
      imageLabel: 'Thêm ảnh',
      imageDescription: 'Nếu bạn có ảnh như phát ban, vết thương hoặc vỏ thuốc, những ảnh đó có thể giúp chúng tôi hiểu rõ hơn tình trạng của bạn.\nBạn có thể tải lên tối đa 3 ảnh, mỗi ảnh tối đa 10MB.',
      imageChooseLabel: 'Chọn tệp',
      imageEmptyLabel: 'Chưa chọn tệp nào',
      imageSelectedLabel: 'Đã chọn {count} tệp',
      notificationTitle: 'Để lại số điện thoại để nhận thông báo phản hồi',
      notificationDescription: 'Tùy chọn. Chúng tôi chỉ dùng liên hệ này nếu bạn đồng ý nhận thông báo khi có phản hồi.',
      phoneLabel: 'Số điện thoại',
      phonePlaceholder: 'Ví dụ: +82 10-1234-5678',
      policyNote: 'Nếu cảm thấy đây là tình huống khẩn cấp, vui lòng liên hệ dịch vụ cấp cứu trước. Happy Doctor không thay thế chăm sóc cấp cứu. Đây là dịch vụ hỗ trợ trực tuyến dành cho những người cần xin trợ giúp trước khi việc tiếp cận y tế trở nên khó khăn hơn.',
      submitLoading: 'Bodeum đang sắp xếp nội dung tư vấn của bạn...',
      submitIdle: 'Bắt đầu tư vấn trên web',
      englishSupportNote: 'Trang này đã được dịch sang ngôn ngữ bạn chọn. Một số chi tiết y khoa vẫn có thể cần làm rõ ở các phản hồi tiếp theo.',
    },
    genderOptionLabels: ['Nữ', 'Nam', 'Khác', 'Không muốn trả lời'],
  }),
  'zh-cn': createBundle({
    page: {
      eyebrow: 'Happy Doctor 咨询开始',
      title: '在网页上开始咨询',
      description: '只需填写必要信息，我们就会为您开启咨询，并提供状态链接和查询代码。',
      homeLabel: '英文主页',
      statusLabel: '查看状态',
      heroEyebrow: '求助入口',
      heroTitle: '当医疗看起来很遥远时\n先把情况说明清楚的地方',
      heroBody: '这个页面是在线医疗支持入口，适合那些在还不知道该向谁求助之前，先需要说明自己状况的人。',
      infoTitle: '请告诉我们',
      infoItems: [
        '现在最不舒服的症状是什么',
        '从什么时候开始的',
        '是否有慢性病或正在服用的药物',
      ],
      supportEyebrow: '如何进行',
      supportTitle: '请用您的语言填写',
      supportItems: [
        '如果症状看起来很紧急，请先联系急救服务。',
        '您可以使用为此页面选择的语言填写。',
        '我们会尽量把您的信息自动翻译给医生。',
      ],
    },
    form: {
      recentEyebrow: '最近的咨询',
      recentBody: '您最近开始的咨询会保留一小时。\n您可以使用代码 {code} 继续。',
      recentLink: '继续最近的咨询',
      restoredDraft: '我们已恢复您刚才输入的内容，您可以继续填写并提交咨询。',
      languageHintEyebrow: '语言支持',
      languageHintTitle: '您可以使用 {language} 填写。',
      languageHintBody: '我们会尽量自动识别 {language} 内容，为医生翻译成韩语，并在可能的情况下用相同语言返回翻译后的回复。',
      phoneConsentRequired: '如果您希望收到回复提醒，请输入电话号码。',
      phoneConsentMismatch: '只有在您选择接收回复提醒时，我们才会保存该联系号码。',
      submitError: '目前无法开始咨询，请稍后再试。',
      ageLabel: '年龄或年龄段',
      agePlaceholder: '例如：40多岁，27岁',
      genderLabel: '性别',
      genderPlaceholder: '不想说明',
      chiefComplaintLabel: '主要症状',
      chiefComplaintPlaceholder: '例如：胃痛、咳嗽、发烧',
      onsetLabel: '什么时候开始的？',
      onsetPlaceholder: '例如：今天早上，3天前',
      nrsLabel: '疼痛或症状评分',
      nrsUnknown: '不确定',
      symptomDetailLabel: '请再多告诉我们一些',
      symptomDetailPlaceholder: '请描述哪里不舒服，以及您现在最担心的是什么。',
      associatedLabel: '伴随症状',
      associatedPlaceholder: '例如：呕吐、发烧、腹泻、咳嗽',
      historyLabel: '病史或正在服用的药物',
      historyPlaceholder: '如果有慢性病或正在服用的药物，请告诉我们。',
      imageLabel: '添加照片',
      imageDescription: '如果您有皮疹、伤口或药盒等照片，这些照片可以帮助我们更好地了解您的情况。\n最多可上传3张图片，每张不超过10MB。',
      imageChooseLabel: '选择文件',
      imageEmptyLabel: '未选择文件',
      imageSelectedLabel: '已选择 {count} 个文件',
      notificationTitle: '留下电话号码以接收回复提醒',
      notificationDescription: '可选。只有在您同意接收回复提醒时，我们才会使用这个联系方式。',
      phoneLabel: '电话号码',
      phonePlaceholder: '例如：+82 10-1234-5678',
      policyNote: '如果您感觉情况紧急，请优先联系急救服务。Happy Doctor 不能替代急诊服务。它是一项在线支持服务，帮助那些在获得医疗变得更困难之前需要先求助的人。',
      submitLoading: 'Bodeum 正在整理您的咨询内容……',
      submitIdle: '在网页上开始咨询',
      englishSupportNote: '此页面已翻译为您选择的语言。后续回复中，某些医学细节仍可能需要进一步说明。',
    },
    genderOptionLabels: ['女性', '男性', '其他', '不想说明'],
  }),
  'zh-tw': createBundle({
    page: {
      eyebrow: 'Happy Doctor 諮詢開始',
      title: '在網頁上開始諮詢',
      description: '只要填寫必要資訊，我們就會為您建立諮詢，並提供狀態連結與查詢代碼。',
      homeLabel: '英文首頁',
      statusLabel: '查看狀態',
      heroEyebrow: '求助入口',
      heroTitle: '當醫療感覺很遙遠時\n可以先把情況說清楚的地方',
      heroBody: '這個頁面是線上醫療支援入口，適合那些在還不知道該向誰求助之前，先需要說明自己狀況的人。',
      infoTitle: '請告訴我們',
      infoItems: [
        '現在最不舒服的是什麼',
        '從什麼時候開始',
        '是否有慢性疾病或正在服用的藥物',
      ],
      supportEyebrow: '如何進行',
      supportTitle: '請用您的語言填寫',
      supportItems: [
        '如果症狀看起來很緊急，請先使用急救服務。',
        '您可以使用此頁面所選的語言填寫。',
        '我們會盡量自動將您的訊息翻譯給醫師。',
      ],
    },
    form: {
      recentEyebrow: '最近的諮詢',
      recentBody: '您最近開始的諮詢會保留一小時。\n您可以使用代碼 {code} 繼續。',
      recentLink: '繼續最近的諮詢',
      restoredDraft: '我們已恢復您剛才輸入的內容，您可以繼續填寫並送出諮詢。',
      languageHintEyebrow: '語言支援',
      languageHintTitle: '您可以使用 {language} 填寫。',
      languageHintBody: '我們會盡量自動辨識 {language} 內容，為醫師翻譯成韓文，並在可能的情況下用相同語言回傳翻譯後的回覆。',
      phoneConsentRequired: '如果您想接收回覆提醒，請輸入電話號碼。',
      phoneConsentMismatch: '只有在您選擇接收回覆提醒時，我們才會保存此聯絡方式。',
      submitError: '目前無法開始諮詢，請稍後再試。',
      ageLabel: '年齡或年齡區間',
      agePlaceholder: '例如：40多歲、27歲',
      genderLabel: '性別',
      genderPlaceholder: '不想透露',
      chiefComplaintLabel: '主要症狀',
      chiefComplaintPlaceholder: '例如：腹痛、咳嗽、發燒',
      onsetLabel: '什麼時候開始的？',
      onsetPlaceholder: '例如：今天早上、3天前',
      nrsLabel: '疼痛或症狀分數',
      nrsUnknown: '不確定',
      symptomDetailLabel: '請再多說一些',
      symptomDetailPlaceholder: '請描述哪裡不舒服，以及您現在最擔心的是什麼。',
      associatedLabel: '其他症狀',
      associatedPlaceholder: '例如：嘔吐、發燒、腹瀉、咳嗽',
      historyLabel: '病史或正在服用的藥物',
      historyPlaceholder: '如果有慢性疾病或正在服用的藥物，請告訴我們。',
      imageLabel: '新增照片',
      imageDescription: '如果您有皮疹、傷口或藥品包裝等照片，這些照片可以幫助我們更了解您的狀況。\n最多可上傳3張圖片，每張不超過10MB。',
      imageChooseLabel: '選擇檔案',
      imageEmptyLabel: '尚未選擇檔案',
      imageSelectedLabel: '已選擇 {count} 個檔案',
      notificationTitle: '留下電話號碼以接收回覆提醒',
      notificationDescription: '選填。只有在您同意接收回覆提醒時，我們才會使用這個聯絡方式。',
      phoneLabel: '電話號碼',
      phonePlaceholder: '例如：+82 10-1234-5678',
      policyNote: '如果您覺得情況緊急，請優先使用急救服務。Happy Doctor 不是急診替代服務，而是幫助那些在獲得醫療變得更困難之前，先在線上尋求協助的人。',
      submitLoading: 'Bodeum 正在整理您的諮詢內容……',
      submitIdle: '在網頁上開始諮詢',
      englishSupportNote: '此頁面已翻譯成您選擇的語言。後續回覆中，部分醫療細節仍可能需要進一步說明。',
    },
    genderOptionLabels: ['女性', '男性', '其他', '不想透露'],
  }),
  ja: createBundle({
    page: {
      eyebrow: 'Happy Doctor 相談開始',
      title: 'ウェブで相談を始める',
      description: '必要な情報だけ入力してください。状態確認リンクと照会コード付きで相談を開始します。',
      homeLabel: '英語ホームページ',
      statusLabel: '状態を確認',
      heroEyebrow: '相談の入口',
      heroTitle: '医療が遠く感じるとき\nまず説明できる場所',
      heroBody: 'このページは、どこに助けを求めればよいか分からないときに、まず状況を説明できるオンライン医療相談の入口です。',
      infoTitle: '教えてください',
      infoItems: [
        '今いちばんつらい症状',
        'いつから始まったか',
        '持病や服用中の薬があるか',
      ],
      supportEyebrow: '進め方',
      supportTitle: 'ご自身の言葉で書いてください',
      supportItems: [
        '症状が緊急だと感じる場合は、まず救急サービスを利用してください。',
        'このページで選んだ言語で入力できます。',
        '医師のために自動翻訳をできる限り行います。',
      ],
    },
    form: {
      recentEyebrow: '最近の相談',
      recentBody: '最近開始した相談は1時間利用できます。\nコード {code} で続けられます。',
      recentLink: '最近の相談を続ける',
      restoredDraft: '入力していた内容を復元しました。そのまま続けて相談を送信できます。',
      languageHintEyebrow: '言語サポート',
      languageHintTitle: '{language} で入力できます。',
      languageHintBody: '{language} の入力は自動で検出し、医師には韓国語に翻訳して共有し、可能な場合は同じ言語で翻訳した返信を返します。',
      phoneConsentRequired: '返信通知を受け取りたい場合は電話番号を入力してください。',
      phoneConsentMismatch: '返信通知の連絡先は、受信に同意した場合のみ保存します。',
      submitError: '現在は相談を開始できません。少し時間をおいてもう一度お試しください。',
      ageLabel: '年齢または年齢層',
      agePlaceholder: '例: 40代、27歳',
      genderLabel: '性別',
      genderPlaceholder: '回答しない',
      chiefComplaintLabel: '主な症状',
      chiefComplaintPlaceholder: '例: 腹痛、せき、発熱',
      onsetLabel: 'いつからですか？',
      onsetPlaceholder: '例: 今朝から、3日前から',
      nrsLabel: '痛み・症状の点数',
      nrsUnknown: 'わからない',
      symptomDetailLabel: '詳しく教えてください',
      symptomDetailPlaceholder: 'どこがどのようにつらいか、今いちばん心配なことは何かを書いてください。',
      associatedLabel: 'ほかにある症状',
      associatedPlaceholder: '例: 嘔吐、発熱、下痢、せき',
      historyLabel: '持病または服用中の薬',
      historyPlaceholder: '持病や服用中の薬があれば書いてください。',
      imageLabel: '写真を追加',
      imageDescription: '発疹、傷、薬のパッケージなどの写真があれば、状況をより正確に理解する助けになります。\n最大3枚、1枚あたり10MBまでアップロードできます。',
      imageChooseLabel: 'ファイルを選択',
      imageEmptyLabel: 'ファイルが選択されていません',
      imageSelectedLabel: '{count} 件のファイルを選択しました',
      notificationTitle: '返信通知用の電話番号を残す',
      notificationDescription: '任意です。返信通知の受信に同意した場合のみ、この連絡先を使用します。',
      phoneLabel: '電話番号',
      phonePlaceholder: '例: +82 10-1234-5678',
      policyNote: '緊急だと感じる場合は、まず救急サービスを利用してください。Happy Doctor は救急医療の代わりではありません。医療へのアクセスがさらに難しくなる前に、オンラインで先に助けを求められるよう支えるサービスです。',
      submitLoading: 'Bodeum が相談内容を整理しています…',
      submitIdle: 'ウェブで相談を始める',
      englishSupportNote: 'このページは選択した言語に翻訳されています。医療上の細かなニュアンスについては、その後の返信で追加確認が必要になる場合があります。',
    },
    genderOptionLabels: ['女性', '男性', 'その他', '回答しない'],
  }),
  mn: createBundle({
    page: {
      eyebrow: 'Happy Doctor эхлэл',
      title: 'Вэбээр зөвлөгөө эхлүүлэх',
      description: 'Зөвхөн шаардлагатай мэдээллээ бичээрэй. Бид таны зөвлөгөөг статусын холбоос болон хайх кодтойгоор нээнэ.',
      homeLabel: 'Англи нүүр хуудас',
      statusLabel: 'Төлөв шалгах',
      heroEyebrow: 'Тусламжийн гарц',
      heroTitle: 'Эмнэлэг хол мэт санагдах үед\nюу болж байгааг эхлээд тайлбарлаж болох газар',
      heroBody: 'Энэ хуудас нь хаанаас тусламж хүсэхээ мэдэхээс өмнө нөхцөл байдлаа тайлбарлах шаардлагатай хүмүүст зориулсан онлайн эмнэлгийн тусламжийн эхлэл цэг юм.',
      infoTitle: 'Бидэнд хэлээрэй',
      infoItems: [
        'одоо хамгийн их зовоож байгаа шинж тэмдэг',
        'хэзээнээс эхэлсэн',
        'архаг өвчин эсвэл уудаг эм байгаа эсэх',
      ],
      supportEyebrow: 'Яаж ажилладаг вэ',
      supportTitle: 'Өөрийн хэлээр бичээрэй',
      supportItems: [
        'Хэрэв шинж тэмдэг яаралтай мэт санагдвал эхлээд яаралтай тусламжид хандана уу.',
        'Та энэ хуудсанд сонгосон хэлээрээ бичиж болно.',
        'Бид таны мессежийг эмч нарт автоматаар орчуулахыг хичээнэ.',
      ],
    },
    form: {
      recentEyebrow: 'Саяхны зөвлөгөө',
      recentBody: 'Таны хамгийн сүүлийн зөвлөгөө нэг цагийн турш хадгалагдана.\n{code} кодоор үргэлжлүүлж болно.',
      recentLink: 'Сүүлийн зөвлөгөөг үргэлжлүүлэх',
      restoredDraft: 'Таны бичиж байсан мэдээллийг сэргээсэн тул үргэлжлүүлэн бөглөж илгээж болно.',
      languageHintEyebrow: 'Хэлний дэмжлэг',
      languageHintTitle: 'Та {language} хэлээр бичиж болно.',
      languageHintBody: 'Бид {language} хэлний оролтыг автоматаар илрүүлж, эмч нарт зориулан солонгос хэл рүү орчуулж, боломжтой үед ижил хэлээр орчуулсан хариу буцаана.',
      phoneConsentRequired: 'Хариуны мэдэгдэл авахыг хүсвэл утасны дугаараа оруулна уу.',
      phoneConsentMismatch: 'Хариуны мэдэгдлийн холбоо барих мэдээллийг зөвхөн зөвшөөрсөн үед хадгална.',
      submitError: 'Одоогоор зөвлөгөөг эхлүүлж чадсангүй. Түр хүлээгээд дахин оролдоно уу.',
      ageLabel: 'Нас эсвэл насны бүлэг',
      agePlaceholder: 'Жишээ: 40 гаруй нас, 27 настай',
      genderLabel: 'Хүйс',
      genderPlaceholder: 'Хэлэхгүй',
      chiefComplaintLabel: 'Гол шинж тэмдэг',
      chiefComplaintPlaceholder: 'Жишээ: гэдэс өвдөх, ханиалгах, халуурах',
      onsetLabel: 'Хэзээнээс эхэлсэн бэ?',
      onsetPlaceholder: 'Жишээ: өнөө өглөө, 3 хоногийн өмнөөс',
      nrsLabel: 'Өвдөлт эсвэл шинж тэмдгийн үнэлгээ',
      nrsUnknown: 'Мэдэхгүй',
      symptomDetailLabel: 'Дэлгэрэнгүй хэлээрэй',
      symptomDetailPlaceholder: 'Хаана яаж зовиуртай байгааг, яг одоо хамгийн их санаа зовоож буй зүйлийг бичнэ үү.',
      associatedLabel: 'Дагалдах шинж тэмдэг',
      associatedPlaceholder: 'Жишээ: бөөлжих, халуурах, суулгах, ханиалгах',
      historyLabel: 'Архаг өвчин эсвэл уудаг эм',
      historyPlaceholder: 'Архаг өвчин эсвэл уудаг эм байгаа бол бичнэ үү.',
      imageLabel: 'Зураг нэмэх',
      imageDescription: 'Тууралт, шарх, эмийн сав баглаа боодол зэрэг зураг байвал бидэнд таны байдлыг илүү сайн ойлгоход тусална.\nНэг бүр нь 10MB-аас ихгүй, нийт 3 хүртэл зураг оруулж болно.',
      imageChooseLabel: 'Файл сонгох',
      imageEmptyLabel: 'Файл сонгогдоогүй байна',
      imageSelectedLabel: '{count} файл сонгогдсон',
      notificationTitle: 'Хариуны мэдэгдэл авах утасны дугаар үлдээх',
      notificationDescription: 'Сонголттой. Та мэдэгдэл авахыг зөвшөөрсөн үед л энэ холбоо барих мэдээллийг ашиглана.',
      phoneLabel: 'Утасны дугаар',
      phonePlaceholder: 'Жишээ: +82 10-1234-5678',
      policyNote: 'Хэрэв энэ байдал яаралтай мэт санагдвал эхлээд яаралтай тусламжид хандана уу. Happy Doctor нь яаралтай эмчилгээний оронд биш, харин эмнэлэгт хүрэхээс өмнө онлайнаар тусламж хүсэх боломж олгох дэмжлэгийн үйлчилгээ юм.',
      submitLoading: 'Bodeum таны зөвлөгөөний агуулгыг эмхэлж байна...',
      submitIdle: 'Вэбээр зөвлөгөө эхлүүлэх',
      englishSupportNote: 'Энэ хуудас таны сонгосон хэлээр орчуулагдсан. Эмнэлгийн нарийн утгыг дараагийн хариунд нэмэлтээр тодруулах шаардлага гарч магадгүй.',
    },
    genderOptionLabels: ['Эмэгтэй', 'Эрэгтэй', 'Бусад', 'Хэлэхгүй'],
  }),
  ru: createBundle({
    page: {
      eyebrow: 'Начало консультации Happy Doctor',
      title: 'Начать консультацию на сайте',
      description: 'Укажите только самое важное, и мы откроем вашу консультацию со ссылкой на статус и кодом для проверки.',
      homeLabel: 'Английская главная страница',
      statusLabel: 'Проверить статус',
      heroEyebrow: 'Точка входа',
      heroTitle: 'Место, где можно сначала объяснить ситуацию,\nкогда медицинская помощь кажется далекой',
      heroBody: 'Эта страница — вход в онлайн-медицинскую поддержку для тех, кому нужно сначала объяснить, что происходит, прежде чем они поймут, куда обращаться за помощью.',
      infoTitle: 'Расскажите нам',
      infoItems: [
        'что сейчас беспокоит сильнее всего',
        'когда это началось',
        'есть ли хронические болезни или лекарства, которые вы принимаете',
      ],
      supportEyebrow: 'Как это работает',
      supportTitle: 'Пишите на своем языке',
      supportItems: [
        'Если симптомы кажутся неотложными, сначала обратитесь в экстренную помощь.',
        'Вы можете писать на языке, выбранном для этой страницы.',
        'Мы постараемся автоматически перевести ваше сообщение для врачей.',
      ],
    },
    form: {
      recentEyebrow: 'Недавняя консультация',
      recentBody: 'Ваша последняя консультация будет доступна в течение одного часа.\nВы можете продолжить по коду {code}.',
      recentLink: 'Продолжить недавнюю консультацию',
      restoredDraft: 'Мы восстановили данные, которые вы вводили, чтобы вы могли продолжить и отправить консультацию.',
      languageHintEyebrow: 'Языковая поддержка',
      languageHintTitle: 'Вы можете писать на {language}.',
      languageHintBody: 'Мы постараемся автоматически распознать текст на {language}, перевести его на корейский для врачей и, если получится, вернуть переведенный ответ на том же языке.',
      phoneConsentRequired: 'Введите номер телефона, если хотите получать уведомления о ответе.',
      phoneConsentMismatch: 'Мы сохраняем контакт для уведомления только если вы согласились получать уведомления о ответе.',
      submitError: 'Сейчас не удалось начать консультацию. Пожалуйста, попробуйте еще раз чуть позже.',
      ageLabel: 'Возраст или возрастная группа',
      agePlaceholder: 'Например: около 40 лет, 27 лет',
      genderLabel: 'Пол',
      genderPlaceholder: 'Предпочитаю не отвечать',
      chiefComplaintLabel: 'Основной симптом',
      chiefComplaintPlaceholder: 'Например: боль в животе, кашель, температура',
      onsetLabel: 'Когда это началось?',
      onsetPlaceholder: 'Например: сегодня утром, 3 дня назад',
      nrsLabel: 'Оценка боли или симптомов',
      nrsUnknown: 'Не знаю',
      symptomDetailLabel: 'Расскажите подробнее',
      symptomDetailPlaceholder: 'Опишите, что именно беспокоит вас сейчас и что вызывает наибольшее беспокойство.',
      associatedLabel: 'Другие симптомы',
      associatedPlaceholder: 'Например: рвота, температура, диарея, кашель',
      historyLabel: 'Хронические болезни или лекарства',
      historyPlaceholder: 'Сообщите, если у вас есть хронические заболевания или вы принимаете какие-либо лекарства.',
      imageLabel: 'Добавить фотографии',
      imageDescription: 'Если у вас есть фотографии сыпи, раны или упаковки лекарства, они помогут нам лучше понять вашу ситуацию.\nМожно загрузить до 3 изображений, не более 10 МБ каждое.',
      imageChooseLabel: 'Выбрать файлы',
      imageEmptyLabel: 'Файлы не выбраны',
      imageSelectedLabel: 'Выбрано файлов: {count}',
      notificationTitle: 'Оставить номер телефона для уведомления о ответе',
      notificationDescription: 'Необязательно. Мы используем этот контакт только если вы согласились получать уведомления о ответе.',
      phoneLabel: 'Номер телефона',
      phonePlaceholder: 'Например: +82 10-1234-5678',
      policyNote: 'Если ситуация кажется срочной, сначала обратитесь в экстренную помощь. Happy Doctor не заменяет неотложную помощь. Это онлайн-сервис поддержки для людей, которым нужно попросить о помощи до того, как доступ к медицине станет еще сложнее.',
      submitLoading: 'Bodeum подготавливает вашу консультацию...',
      submitIdle: 'Начать консультацию на сайте',
      englishSupportNote: 'Эта страница уже переведена на выбранный вами язык. Некоторые медицинские нюансы могут потребовать уточнения в последующих ответах.',
    },
    genderOptionLabels: ['Женский', 'Мужской', 'Другое', 'Предпочитаю не отвечать'],
  }),
  th: createBundle({
    page: {
      eyebrow: 'เริ่มต้นกับ Happy Doctor',
      title: 'เริ่มการปรึกษาผ่านเว็บ',
      description: 'กรอกเฉพาะข้อมูลที่จำเป็น แล้วเราจะเปิดการปรึกษาพร้อมลิงก์สถานะและรหัสตรวจสอบให้คุณ',
      homeLabel: 'หน้าแรกภาษาอังกฤษ',
      statusLabel: 'ตรวจสอบสถานะ',
      heroEyebrow: 'จุดเริ่มต้นในการขอความช่วยเหลือ',
      heroTitle: 'ที่ที่คุณอธิบายก่อนได้\nเมื่อการเข้าถึงการรักษาดูเหมือนไกลเกินไป',
      heroBody: 'หน้านี้เป็นจุดเริ่มต้นของการช่วยเหลือทางการแพทย์ออนไลน์สำหรับผู้ที่ต้องอธิบายอาการของตนก่อนที่จะรู้ว่าควรขอความช่วยเหลือจากที่ไหน',
      infoTitle: 'โปรดบอกเรา',
      infoItems: [
        'อาการที่รบกวนคุณมากที่สุดตอนนี้คืออะไร',
        'เริ่มตั้งแต่เมื่อไร',
        'มีโรคประจำตัวหรือยาที่กำลังใช้อยู่หรือไม่',
      ],
      supportEyebrow: 'วิธีการทำงาน',
      supportTitle: 'คุณสามารถเขียนเป็นภาษาของคุณได้',
      supportItems: [
        'หากอาการดูฉุกเฉิน โปรดใช้บริการฉุกเฉินก่อน',
        'คุณสามารถเขียนด้วยภาษาที่เลือกไว้สำหรับหน้านี้ได้',
        'เราจะพยายามแปลข้อความของคุณให้อัตโนมัติสำหรับแพทย์',
      ],
    },
    form: {
      recentEyebrow: 'การปรึกษาล่าสุด',
      recentBody: 'การปรึกษาล่าสุดของคุณจะคงอยู่เป็นเวลา 1 ชั่วโมง\nคุณสามารถดำเนินการต่อด้วยรหัส {code}',
      recentLink: 'ดำเนินการต่อจากการปรึกษาล่าสุด',
      restoredDraft: 'เราได้กู้คืนข้อมูลที่คุณกำลังพิมพ์ไว้ เพื่อให้คุณสามารถกรอกต่อและส่งการปรึกษาได้',
      languageHintEyebrow: 'รองรับภาษา',
      languageHintTitle: 'คุณสามารถเขียนเป็น {language} ได้',
      languageHintBody: 'เราจะพยายามตรวจจับข้อความ {language} โดยอัตโนมัติ แปลเป็นภาษาเกาหลีสำหรับแพทย์ และส่งคำตอบที่แปลแล้วกลับมาเป็นภาษาเดิมหากเป็นไปได้',
      phoneConsentRequired: 'โปรดกรอกหมายเลขโทรศัพท์หากคุณต้องการรับการแจ้งเตือนเมื่อมีคำตอบ',
      phoneConsentMismatch: 'เราจะบันทึกข้อมูลติดต่อเพื่อแจ้งเตือนเฉพาะเมื่อคุณยินยอมรับการแจ้งเตือนเท่านั้น',
      submitError: 'ไม่สามารถเริ่มการปรึกษาได้ในขณะนี้ โปรดลองอีกครั้งในอีกสักครู่',
      ageLabel: 'อายุหรือช่วงอายุ',
      agePlaceholder: 'ตัวอย่าง: วัย 40 ปี, อายุ 27 ปี',
      genderLabel: 'เพศ',
      genderPlaceholder: 'ไม่ต้องการระบุ',
      chiefComplaintLabel: 'อาการหลัก',
      chiefComplaintPlaceholder: 'ตัวอย่าง: ปวดท้อง ไอ มีไข้',
      onsetLabel: 'เริ่มตั้งแต่เมื่อไร',
      onsetPlaceholder: 'ตัวอย่าง: ตั้งแต่เช้านี้, ตั้งแต่ 3 วันที่แล้ว',
      nrsLabel: 'ระดับความปวดหรืออาการ',
      nrsUnknown: 'ไม่แน่ใจ',
      symptomDetailLabel: 'เล่าเพิ่มเติม',
      symptomDetailPlaceholder: 'โปรดอธิบายว่าคุณรู้สึกไม่สบายอย่างไร และตอนนี้กังวลเรื่องใดมากที่สุด',
      associatedLabel: 'อาการอื่นร่วมด้วย',
      associatedPlaceholder: 'ตัวอย่าง: อาเจียน มีไข้ ท้องเสีย ไอ',
      historyLabel: 'โรคประจำตัวหรือยาที่ใช้',
      historyPlaceholder: 'หากมีโรคประจำตัวหรือกำลังใช้ยาใดอยู่ โปรดระบุ',
      imageLabel: 'เพิ่มรูปภาพ',
      imageDescription: 'หากคุณมีรูปผื่น แผล หรือซองยา รูปภาพเหล่านี้จะช่วยให้เราเข้าใจสถานการณ์ของคุณได้ดีขึ้น\nคุณสามารถอัปโหลดรูปภาพได้สูงสุด 3 รูป รูปละไม่เกิน 10MB',
      imageChooseLabel: 'เลือกไฟล์',
      imageEmptyLabel: 'ยังไม่ได้เลือกไฟล์',
      imageSelectedLabel: 'เลือกไฟล์แล้ว {count} ไฟล์',
      notificationTitle: 'ฝากหมายเลขโทรศัพท์สำหรับรับการแจ้งเตือนคำตอบ',
      notificationDescription: 'ไม่บังคับ เราจะใช้ข้อมูลติดต่อดังกล่าวเฉพาะเมื่อคุณยินยอมรับการแจ้งเตือนคำตอบเท่านั้น',
      phoneLabel: 'หมายเลขโทรศัพท์',
      phonePlaceholder: 'ตัวอย่าง: +82 10-1234-5678',
      policyNote: 'หากคุณรู้สึกว่านี่เป็นเหตุฉุกเฉิน โปรดใช้บริการฉุกเฉินก่อน Happy Doctor ไม่ได้ทดแทนการรักษาฉุกเฉิน แต่เป็นบริการสนับสนุนออนไลน์สำหรับผู้ที่ต้องการขอความช่วยเหลือก่อนที่การเข้าถึงการรักษาจะยากขึ้น',
      submitLoading: 'Bodeum กำลังจัดระเบียบข้อมูลการปรึกษาของคุณ...',
      submitIdle: 'เริ่มการปรึกษาผ่านเว็บ',
      englishSupportNote: 'หน้านี้ได้รับการแปลเป็นภาษาที่คุณเลือกแล้ว อย่างไรก็ตาม รายละเอียดทางการแพทย์บางอย่างอาจยังต้องได้รับการชี้แจงเพิ่มเติมในคำตอบถัดไป',
    },
    genderOptionLabels: ['หญิง', 'ชาย', 'อื่น ๆ', 'ไม่ต้องการระบุ'],
  }),
  tl: createBundle({
    page: {
      eyebrow: 'Simula ng Happy Doctor',
      title: 'Simulan ang konsultasyon sa web',
      description: 'Ibahagi lamang ang mahahalagang detalye at bubuksan namin ang iyong konsultasyon kasama ang status link at lookup code.',
      homeLabel: 'English na homepage',
      statusLabel: 'Suriin ang status',
      heroEyebrow: 'Unang hakbang sa paghingi ng tulong',
      heroTitle: 'Isang lugar para magpaliwanag muna\nkapag tila napakalayo ng serbisyong medikal',
      heroBody: 'Ang pahinang ito ay isang online medical support entry point para sa mga taong kailangang ipaliwanag muna ang nangyayari bago nila malaman kung saan hihingi ng tulong.',
      infoTitle: 'Pakisabi sa amin',
      infoItems: [
        'ano ang pinakamatinding sintomas ngayon',
        'kailan ito nagsimula',
        'kung may malalang sakit ka o iniinom na gamot',
      ],
      supportEyebrow: 'Paano ito gumagana',
      supportTitle: 'Maaari kang sumulat sa sarili mong wika',
      supportItems: [
        'Kung mukhang emergency ang mga sintomas, unahin muna ang emergency services.',
        'Maaari kang magsulat gamit ang wikang pinili para sa pahinang ito.',
        'Susubukan naming awtomatikong isalin ang iyong mensahe para sa aming mga doktor.',
      ],
    },
    form: {
      recentEyebrow: 'Kamakailang konsultasyon',
      recentBody: 'Magagamit ang iyong pinakahuling konsultasyon sa loob ng isang oras.\nMaaari kang magpatuloy gamit ang code na {code}.',
      recentLink: 'Ipagpatuloy ang kamakailang konsultasyon',
      restoredDraft: 'Ibinalik namin ang mga detalye na tina-type mo para makapagpatuloy ka at maipasa ang konsultasyon.',
      languageHintEyebrow: 'Suporta sa wika',
      languageHintTitle: 'Maaari kang magsulat sa {language}.',
      languageHintBody: 'Susubukan naming awtomatikong matukoy ang {language} na input, isalin ito sa Korean para sa aming mga doktor, at ibalik ang naisaling sagot sa parehong wika kung maaari.',
      phoneConsentRequired: 'Pakilagay ang numero ng telepono kung gusto mong makatanggap ng abiso kapag may sagot na.',
      phoneConsentMismatch: 'Sine-save lang namin ang contact para sa abiso kapag pumayag kang makatanggap nito.',
      submitError: 'Hindi namin masimulan ang konsultasyon ngayon. Pakisubukang muli pagkalipas ng ilang sandali.',
      ageLabel: 'Edad o pangkat ng edad',
      agePlaceholder: 'Halimbawa: nasa 40s, 27 taong gulang',
      genderLabel: 'Kasarian',
      genderPlaceholder: 'Mas gustong huwag sabihin',
      chiefComplaintLabel: 'Pangunahing sintomas',
      chiefComplaintPlaceholder: 'Halimbawa: pananakit ng tiyan, ubo, lagnat',
      onsetLabel: 'Kailan ito nagsimula?',
      onsetPlaceholder: 'Halimbawa: ngayong umaga, 3 araw na ang nakalipas',
      nrsLabel: 'Antas ng sakit o sintomas',
      nrsUnknown: 'Hindi sigurado',
      symptomDetailLabel: 'Magkuwento pa nang kaunti',
      symptomDetailPlaceholder: 'Ilarawan kung ano ang hindi komportable at ano ang pinakakinababahala mo ngayon.',
      associatedLabel: 'Iba pang sintomas',
      associatedPlaceholder: 'Halimbawa: pagsusuka, lagnat, pagtatae, ubo',
      historyLabel: 'Kasaysayan ng sakit o iniinom na gamot',
      historyPlaceholder: 'Pakisabi kung may chronic na kondisyon o gamot kang iniinom.',
      imageLabel: 'Magdagdag ng mga larawan',
      imageDescription: 'Kung may larawan ka ng pantal, sugat, o pakete ng gamot, makatutulong ito upang mas maintindihan namin ang iyong sitwasyon.\nMaaari kang mag-upload ng hanggang 3 larawan, hanggang 10MB bawat isa.',
      imageChooseLabel: 'Pumili ng mga file',
      imageEmptyLabel: 'Walang napiling file',
      imageSelectedLabel: '{count} file ang napili',
      notificationTitle: 'Mag-iwan ng numero para sa alerto ng sagot',
      notificationDescription: 'Opsyonal. Gagamitin lamang namin ang contact na ito kung pumayag kang makatanggap ng alerto kapag may sagot na.',
      phoneLabel: 'Numero ng telepono',
      phonePlaceholder: 'Halimbawa: +82 10-1234-5678',
      policyNote: 'Kung pakiramdam mo ay emergency ito, unahin muna ang emergency services. Hindi kapalit ng emergency care ang Happy Doctor. Isa itong online support service para sa mga taong kailangang humingi ng tulong bago lalo pang maging mahirap ang pag-access sa pangangalagang medikal.',
      submitLoading: 'Inaayos ni Bodeum ang iyong konsultasyon...',
      submitIdle: 'Simulan ang konsultasyon sa web',
      englishSupportNote: 'Isinalin na ang pahinang ito sa wikang pinili mo. Maaaring kailanganin pa ring linawin ang ilang medikal na detalye sa mga susunod na sagot.',
    },
    genderOptionLabels: ['Babae', 'Lalaki', 'Iba pa', 'Mas gustong huwag sabihin'],
  }),
  ne: createBundle({
    page: {
      eyebrow: 'Happy Doctor सुरु',
      title: 'वेबमा परामर्श सुरु गर्नुहोस्',
      description: 'आवश्यक जानकारी मात्र लेख्नुहोस्, हामी तपाईंको परामर्शलाई स्थिति लिंक र खोज कोडसहित सुरु गर्नेछौं।',
      homeLabel: 'अंग्रेजी गृहपृष्ठ',
      statusLabel: 'स्थिति जाँच गर्नुहोस्',
      heroEyebrow: 'सहायताको प्रवेशद्वार',
      heroTitle: 'स्वास्थ्य सेवा धेरै टाढा जस्तो लाग्दा\nपहिले आफ्नो अवस्था बताउन सकिने ठाउँ',
      heroBody: 'यो पृष्ठ अनलाइन चिकित्सकीय सहयोगको प्रवेशद्वार हो, जहाँ कहाँ मद्दत माग्ने भन्ने थाहा पाउनु अघि आफ्नो अवस्था बताउनुपर्ने मानिसहरू आउन सक्छन्।',
      infoTitle: 'हामीलाई बताउनुहोस्',
      infoItems: [
        'अहिले सबैभन्दा धेरै सताइरहेको लक्षण के हो',
        'कहिलेदेखि सुरु भयो',
        'दीर्घरोग वा खाइरहनुभएको औषधि छ कि छैन',
      ],
      supportEyebrow: 'यसरी काम गर्छ',
      supportTitle: 'आफ्नै भाषामा लेख्नुहोस्',
      supportItems: [
        'यदि लक्षण आकस्मिक जस्तो लाग्छ भने, पहिले आपत्कालीन सेवामा सम्पर्क गर्नुहोस्।',
        'यो पृष्ठका लागि तपाईंले रोजेको भाषामा लेख्न सक्नुहुन्छ।',
        'हामी तपाईंको सन्देशलाई चिकित्सकहरूका लागि स्वचालित रूपमा अनुवाद गर्ने प्रयास गर्नेछौं।',
      ],
    },
    form: {
      recentEyebrow: 'हालैको परामर्श',
      recentBody: 'तपाईंको हालैको परामर्श एक घण्टासम्म उपलब्ध रहनेछ।\nतपाईं {code} कोड प्रयोग गरेर जारी राख्न सक्नुहुन्छ।',
      recentLink: 'हालैको परामर्श जारी राख्नुहोस्',
      restoredDraft: 'तपाईंले लेखिरहनुभएको विवरण हामीले फर्काइदिएका छौं, त्यसैले तपाईं जारी राखेर परामर्श पठाउन सक्नुहुन्छ।',
      languageHintEyebrow: 'भाषा सहयोग',
      languageHintTitle: 'तपाईं {language} मा लेख्न सक्नुहुन्छ।',
      languageHintBody: 'हामी {language} इनपुटलाई स्वचालित रूपमा पहिचान गर्ने, चिकित्सकहरूका लागि कोरियनमा अनुवाद गर्ने, र सम्भव भएमा सोही भाषामा अनुवादित जवाफ फर्काउने प्रयास गर्नेछौं।',
      phoneConsentRequired: 'जवाफको सूचना चाहनुहुन्छ भने कृपया फोन नम्बर लेख्नुहोस्।',
      phoneConsentMismatch: 'हामी सूचना प्राप्त गर्न सहमति दिएको अवस्थामा मात्र सम्पर्क जानकारी सुरक्षित गर्छौं।',
      submitError: 'अहिले परामर्श सुरु गर्न सकिएन। कृपया केही बेरपछि फेरि प्रयास गर्नुहोस्।',
      ageLabel: 'उमेर वा उमेर समूह',
      agePlaceholder: 'उदाहरण: ४० वर्षतिर, २७ वर्ष',
      genderLabel: 'लिङ्ग',
      genderPlaceholder: 'बताउन चाहन्न',
      chiefComplaintLabel: 'मुख्य लक्षण',
      chiefComplaintPlaceholder: 'उदाहरण: पेट दुख्ने, खोकी, ज्वरो',
      onsetLabel: 'कहिलेदेखि सुरु भयो?',
      onsetPlaceholder: 'उदाहरण: आज बिहानदेखि, ३ दिनअघि देखि',
      nrsLabel: 'दुखाइ वा लक्षणको स्तर',
      nrsUnknown: 'थाहा छैन',
      symptomDetailLabel: 'अझ विस्तारमा लेख्नुहोस्',
      symptomDetailPlaceholder: 'कहाँ कस्तो असहजता छ र अहिले सबैभन्दा बढी के कुराले चिन्ता दिएको छ, लेख्नुहोस्।',
      associatedLabel: 'साथमा भएका अन्य लक्षण',
      associatedPlaceholder: 'उदाहरण: बान्ता, ज्वरो, पखाला, खोकी',
      historyLabel: 'दीर्घरोग वा खाइरहनुभएको औषधि',
      historyPlaceholder: 'यदि दीर्घरोग वा औषधि छ भने कृपया लेख्नुहोस्।',
      imageLabel: 'तस्बिर थप्नुहोस्',
      imageDescription: 'यदि तपाईंसँग र्‍यास, घाउ वा औषधिको प्याकेज जस्ता तस्बिर छन् भने, त्यसले हामीलाई तपाईंको अवस्था अझ राम्रो बुझ्न मद्दत गर्छ।\nअधिकतम ३ वटा तस्बिर, प्रत्येक १०MB सम्म अपलोड गर्न सक्नुहुन्छ।',
      imageChooseLabel: 'फाइल छान्नुहोस्',
      imageEmptyLabel: 'कुनै फाइल चयन गरिएको छैन',
      imageSelectedLabel: '{count} वटा फाइल चयन गरियो',
      notificationTitle: 'जवाफ सूचनाका लागि फोन नम्बर छोड्नुहोस्',
      notificationDescription: 'वैकल्पिक। तपाईंले सहमति दिएको अवस्थामा मात्र हामी यो सम्पर्क जानकारी जवाफ सूचनाका लागि प्रयोग गर्छौं।',
      phoneLabel: 'फोन नम्बर',
      phonePlaceholder: 'उदाहरण: +82 10-1234-5678',
      policyNote: 'यदि यो आकस्मिक अवस्था जस्तो लाग्छ भने, पहिले आपत्कालीन सेवामा सम्पर्क गर्नुहोस्। Happy Doctor आकस्मिक उपचारको विकल्प होइन। यो त्यस्ता मानिसहरूका लागि अनलाइन सहयोग सेवा हो, जसलाई स्वास्थ्य सेवामा पहुँच अझ कठिन हुनु अघि मद्दत माग्न आवश्यक हुन्छ।',
      submitLoading: 'Bodeum ले तपाईंको परामर्श व्यवस्थित गर्दैछ...',
      submitIdle: 'वेबमा परामर्श सुरु गर्नुहोस्',
      englishSupportNote: 'यो पृष्ठ तपाईंले रोजेको भाषामा अनुवाद गरिएको छ। केही चिकित्सकीय सूक्ष्मताहरूलाई पछिका उत्तरहरूमा थप स्पष्टिकरण चाहिन सक्छ।',
    },
    genderOptionLabels: ['महिला', 'पुरुष', 'अन्य', 'बताउन चाहन्न'],
  }),
  km: createBundle({
    page: {
      eyebrow: 'ចាប់ផ្តើមជាមួយ Happy Doctor',
      title: 'ចាប់ផ្តើមការពិគ្រោះតាមវេបសាយ',
      description: 'សូមចែករំលែកតែព័ត៌មានចាំបាច់ ហើយយើងនឹងបើកការពិគ្រោះរបស់អ្នកជាមួយតំណស្ថានភាព និងកូដស្វែងរក។',
      homeLabel: 'ទំព័រដើមភាសាអង់គ្លេស',
      statusLabel: 'ពិនិត្យស្ថានភាព',
      heroEyebrow: 'ច្រកចូលសម្រាប់ស្នើជំនួយ',
      heroTitle: 'កន្លែងមួយសម្រាប់ពន្យល់ជាមុន\nនៅពេលដែលសេវាសុខាភិបាលហាក់ដូចជាឆ្ងាយពេក',
      heroBody: 'ទំព័រនេះគឺជាច្រកចូលសម្រាប់ការគាំទ្រផ្នែកវេជ្ជសាស្ត្រតាមអ៊ីនធឺណិត សម្រាប់អ្នកដែលត្រូវការពន្យល់អំពីអ្វីកំពុងកើតឡើង មុនពេលដឹងថាត្រូវសុំជំនួយនៅទីណា។',
      infoTitle: 'សូមប្រាប់យើង',
      infoItems: [
        'អ្វីដែលធ្វើឱ្យអ្នកមិនស្រួលបំផុតឥឡូវនេះ',
        'វាចាប់ផ្តើមតាំងពីពេលណា',
        'តើអ្នកមានជំងឺរ៉ាំរ៉ៃ ឬកំពុងប្រើថ្នាំអ្វីខ្លះដែរឬទេ',
      ],
      supportEyebrow: 'របៀបដំណើរការ',
      supportTitle: 'សូមសរសេរជាភាសារបស់អ្នក',
      supportItems: [
        'បើរោគសញ្ញាមើលទៅបន្ទាន់ សូមទាក់ទងសេវាសង្គ្រោះបន្ទាន់ជាមុនសិន។',
        'អ្នកអាចសរសេរជាភាសាដែលបានជ្រើសរើសសម្រាប់ទំព័រនេះ។',
        'យើងនឹងព្យាយាមបកប្រែសាររបស់អ្នកដោយស្វ័យប្រវត្តិសម្រាប់វេជ្ជបណ្ឌិត។',
      ],
    },
    form: {
      recentEyebrow: 'ការពិគ្រោះថ្មីៗ',
      recentBody: 'ការពិគ្រោះថ្មីបំផុតរបស់អ្នកនឹងអាចមើលបានរយៈពេលមួយម៉ោង។\nអ្នកអាចបន្តដោយប្រើកូដ {code}។',
      recentLink: 'បន្តការពិគ្រោះថ្មីៗ',
      restoredDraft: 'យើងបានស្ដារព័ត៌មានដែលអ្នកកំពុងវាយ ដូច្នេះអ្នកអាចបន្ត និងផ្ញើការពិគ្រោះបាន។',
      languageHintEyebrow: 'ការគាំទ្រភាសា',
      languageHintTitle: 'អ្នកអាចសរសេរជា {language}។',
      languageHintBody: 'យើងនឹងព្យាយាមស្គាល់អត្ថបទ {language} ដោយស្វ័យប្រវត្តិ បកប្រែវាទៅជាភាសាកូរ៉េសម្រាប់វេជ្ជបណ្ឌិត ហើយបើអាច យើងនឹងផ្ញើការឆ្លើយតបដែលបានបកប្រែក្នុងភាសាដដែលត្រឡប់មកវិញ។',
      phoneConsentRequired: 'សូមបញ្ចូលលេខទូរស័ព្ទ ប្រសិនបើអ្នកចង់ទទួលការជូនដំណឹងពេលមានការឆ្លើយតប។',
      phoneConsentMismatch: 'យើងរក្សាទុកទំនាក់ទំនងសម្រាប់ការជូនដំណឹងតែពេលអ្នកយល់ព្រមទទួលការជូនដំណឹងប៉ុណ្ណោះ។',
      submitError: 'មិនអាចចាប់ផ្តើមការពិគ្រោះបាននៅពេលនេះទេ។ សូមព្យាយាមម្តងទៀតបន្តិចក្រោយ។',
      ageLabel: 'អាយុ ឬក្រុមអាយុ',
      agePlaceholder: 'ឧទាហរណ៍៖ អាយុជាង 40 ឆ្នាំ, 27 ឆ្នាំ',
      genderLabel: 'ភេទ',
      genderPlaceholder: 'មិនចង់បញ្ជាក់',
      chiefComplaintLabel: 'រោគសញ្ញាចម្បង',
      chiefComplaintPlaceholder: 'ឧទាហរណ៍៖ ឈឺពោះ ក្អក គ្រុនក្តៅ',
      onsetLabel: 'វាចាប់ផ្តើមពីពេលណា?',
      onsetPlaceholder: 'ឧទាហរណ៍៖ ព្រឹកនេះ ចាប់ពី 3 ថ្ងៃមុន',
      nrsLabel: 'កម្រិតឈឺ ឬរោគសញ្ញា',
      nrsUnknown: 'មិនប្រាកដ',
      symptomDetailLabel: 'សូមប្រាប់លម្អិតបន្ថែម',
      symptomDetailPlaceholder: 'សូមពិពណ៌នាថាតើកន្លែងណា និងយ៉ាងដូចម្តេចដែលមិនស្រួល ហើយអ្វីដែលអ្នកព្រួយបារម្ភបំផុតឥឡូវនេះ។',
      associatedLabel: 'រោគសញ្ញាផ្សេងទៀត',
      associatedPlaceholder: 'ឧទាហរណ៍៖ ក្អួត គ្រុនក្តៅ រាគ ក្អក',
      historyLabel: 'ជំងឺរ៉ាំរ៉ៃ ឬថ្នាំកំពុងប្រើ',
      historyPlaceholder: 'ប្រសិនបើមានជំងឺរ៉ាំរ៉ៃ ឬថ្នាំកំពុងប្រើ សូមសរសេរប្រាប់យើង។',
      imageLabel: 'បន្ថែមរូបថត',
      imageDescription: 'ប្រសិនបើអ្នកមានរូបថតដូចជា ផ្ទៃកន្ទួល របួស ឬកញ្ចប់ថ្នាំ វាអាចជួយឱ្យយើងយល់ស្ថានភាពរបស់អ្នកបានកាន់តែល្អ។\nអ្នកអាចអាប់ឡូដរូបភាពបានរហូតដល់ 3 រូប និងមួយរូបមិនលើស 10MB។',
      imageChooseLabel: 'ជ្រើសឯកសារ',
      imageEmptyLabel: 'មិនទាន់បានជ្រើសឯកសារ',
      imageSelectedLabel: 'បានជ្រើស {count} ឯកសារ',
      notificationTitle: 'ទុកលេខទូរស័ព្ទសម្រាប់ការជូនដំណឹងពេលមានការឆ្លើយតប',
      notificationDescription: 'ជាជម្រើស។ យើងប្រើព័ត៌មានទំនាក់ទំនងនេះតែពេលអ្នកយល់ព្រមទទួលការជូនដំណឹងប៉ុណ្ណោះ។',
      phoneLabel: 'លេខទូរស័ព្ទ',
      phonePlaceholder: 'ឧទាហរណ៍៖ +82 10-1234-5678',
      policyNote: 'បើអ្នកមានអារម្មណ៍ថាវាជាស្ថានភាពបន្ទាន់ សូមប្រើសេវាសង្គ្រោះបន្ទាន់ជាមុនសិន។ Happy Doctor មិនមែនជាការជំនួសសម្រាប់ការព្យាបាលបន្ទាន់ទេ ប៉ុន្តែជាសេវាគាំទ្រតាមអ៊ីនធឺណិតសម្រាប់អ្នកដែលត្រូវការសុំជំនួយ មុនពេលការចូលដំណើរការការថែទាំសុខភាពកាន់តែពិបាក។',
      submitLoading: 'Bodeum កំពុងរៀបចំខ្លឹមសារការពិគ្រោះរបស់អ្នក...',
      submitIdle: 'ចាប់ផ្តើមការពិគ្រោះតាមវេបសាយ',
      englishSupportNote: 'ទំព័រនេះត្រូវបានបកប្រែជាភាសាដែលអ្នកបានជ្រើសរើសរួចហើយ។ ចម្លើយបន្ទាប់ៗអាចនៅតែត្រូវការការបញ្ជាក់បន្ថែមលើពាក្យពេចន៍វេជ្ជសាស្ត្រ។',
    },
    genderOptionLabels: ['ស្រី', 'ប្រុស', 'ផ្សេងទៀត', 'មិនចង់បញ្ជាក់'],
  }),
  id: createBundle({
    page: {
      eyebrow: 'Mulai dengan Happy Doctor',
      title: 'Mulai konsultasi di web',
      description: 'Bagikan hanya informasi yang penting dan kami akan membuka konsultasi Anda dengan tautan status serta kode pemeriksaan.',
      homeLabel: 'Beranda bahasa Inggris',
      statusLabel: 'Periksa status',
      heroEyebrow: 'Pintu masuk bantuan',
      heroTitle: 'Tempat untuk menjelaskan lebih dulu\nketika layanan kesehatan terasa jauh',
      heroBody: 'Halaman ini adalah pintu masuk dukungan medis online bagi orang-orang yang perlu menjelaskan apa yang sedang terjadi sebelum mereka tahu harus meminta bantuan ke mana.',
      infoTitle: 'Tolong beri tahu kami',
      infoItems: [
        'gejala yang paling mengganggu saat ini',
        'sejak kapan dimulai',
        'apakah Anda memiliki penyakit kronis atau sedang minum obat',
      ],
      supportEyebrow: 'Cara kerjanya',
      supportTitle: 'Silakan tulis dalam bahasa Anda',
      supportItems: [
        'Jika gejalanya terasa darurat, mohon gunakan layanan darurat terlebih dahulu.',
        'Anda dapat menulis dalam bahasa yang dipilih untuk halaman ini.',
        'Kami akan mencoba menerjemahkan pesan Anda secara otomatis untuk dokter kami.',
      ],
    },
    form: {
      recentEyebrow: 'Konsultasi terbaru',
      recentBody: 'Konsultasi terbaru Anda akan tersedia selama satu jam.\nAnda dapat melanjutkan dengan kode {code}.',
      recentLink: 'Lanjutkan konsultasi terbaru',
      restoredDraft: 'Kami memulihkan rincian yang sedang Anda tulis agar Anda dapat melanjutkan dan mengirimkan konsultasi.',
      languageHintEyebrow: 'Dukungan bahasa',
      languageHintTitle: 'Anda dapat menulis dalam {language}.',
      languageHintBody: 'Kami akan mencoba mendeteksi input {language} secara otomatis, menerjemahkannya ke bahasa Korea untuk dokter kami, lalu mengirimkan balasan yang diterjemahkan dalam bahasa yang sama jika memungkinkan.',
      phoneConsentRequired: 'Silakan masukkan nomor telepon jika Anda ingin menerima notifikasi balasan.',
      phoneConsentMismatch: 'Kami hanya menyimpan kontak notifikasi balasan jika Anda setuju untuk menerimanya.',
      submitError: 'Kami belum bisa memulai konsultasi sekarang. Silakan coba lagi beberapa saat lagi.',
      ageLabel: 'Usia atau rentang usia',
      agePlaceholder: 'Contoh: usia 40-an, 27 tahun',
      genderLabel: 'Jenis kelamin',
      genderPlaceholder: 'Memilih untuk tidak menyebutkan',
      chiefComplaintLabel: 'Gejala utama',
      chiefComplaintPlaceholder: 'Contoh: sakit perut, batuk, demam',
      onsetLabel: 'Kapan mulai terasa?',
      onsetPlaceholder: 'Contoh: pagi ini, sejak 3 hari lalu',
      nrsLabel: 'Skor nyeri atau gejala',
      nrsUnknown: 'Tidak yakin',
      symptomDetailLabel: 'Ceritakan lebih rinci',
      symptomDetailPlaceholder: 'Mohon jelaskan bagian mana yang terasa tidak nyaman dan apa yang paling Anda khawatirkan sekarang.',
      associatedLabel: 'Gejala lain',
      associatedPlaceholder: 'Contoh: muntah, demam, diare, batuk',
      historyLabel: 'Riwayat penyakit atau obat',
      historyPlaceholder: 'Jika Anda memiliki penyakit kronis atau sedang minum obat, mohon tuliskan.',
      imageLabel: 'Tambahkan foto',
      imageDescription: 'Jika Anda memiliki foto seperti ruam, luka, atau kemasan obat, foto tersebut dapat membantu kami memahami situasi Anda dengan lebih baik.\nAnda dapat mengunggah hingga 3 gambar, masing-masing maksimal 10MB.',
      imageChooseLabel: 'Pilih file',
      imageEmptyLabel: 'Belum ada file yang dipilih',
      imageSelectedLabel: '{count} file dipilih',
      notificationTitle: 'Tinggalkan nomor telepon untuk menerima notifikasi balasan',
      notificationDescription: 'Opsional. Kami hanya menggunakan kontak ini jika Anda setuju menerima notifikasi saat ada balasan.',
      phoneLabel: 'Nomor telepon',
      phonePlaceholder: 'Contoh: +82 10-1234-5678',
      policyNote: 'Jika situasi ini terasa darurat, mohon gunakan layanan darurat terlebih dahulu. Happy Doctor bukan pengganti perawatan darurat. Ini adalah layanan dukungan online bagi orang-orang yang perlu meminta bantuan sebelum akses ke layanan kesehatan menjadi semakin sulit.',
      submitLoading: 'Bodeum sedang merapikan isi konsultasi Anda...',
      submitIdle: 'Mulai konsultasi di web',
      englishSupportNote: 'Halaman ini sudah diterjemahkan ke bahasa yang Anda pilih. Beberapa nuansa medis mungkin masih perlu diperjelas pada balasan berikutnya.',
    },
    genderOptionLabels: ['Perempuan', 'Laki-laki', 'Lainnya', 'Memilih untuk tidak menyebutkan'],
  }),
  uz: createBundle({
    page: {
      eyebrow: 'Happy Doctor bilan boshlash',
      title: 'Veb orqali maslahatni boshlang',
      description: 'Faqat kerakli maʼlumotlarni yozing, biz maslahatni holat havolasi va tekshirish kodi bilan ochamiz.',
      homeLabel: 'Inglizcha bosh sahifa',
      statusLabel: 'Holatni tekshirish',
      heroEyebrow: 'Yordamga kirish nuqtasi',
      heroTitle: 'Tibbiy yordam juda uzoqdek tuyulganda\navval holatni tushuntirib olish mumkin bo‘lgan joy',
      heroBody: 'Bu sahifa qayerdan yordam so‘rashni bilishdan oldin holatini tushuntirishga muhtoj bo‘lgan odamlar uchun onlayn tibbiy yordam kirish nuqtasidir.',
      infoTitle: 'Bizga ayting',
      infoItems: [
        'hozir sizni eng ko‘p bezovta qilayotgan alomat nima',
        'qachondan boshlangan',
        'surunkali kasallik yoki qabul qilayotgan dorilar bor-yo‘qligi',
      ],
      supportEyebrow: 'Qanday ishlaydi',
      supportTitle: 'O‘z tilingizda yozing',
      supportItems: [
        'Agar alomatlar shoshilinchdek tuyulsa, avval tez yordam xizmatidan foydalaning.',
        'Siz bu sahifa uchun tanlangan tilda yozishingiz mumkin.',
        'Biz xabaringizni shifokorlar uchun avtomatik tarjima qilishga harakat qilamiz.',
      ],
    },
    form: {
      recentEyebrow: 'Yaqindagi maslahat',
      recentBody: 'Sizning eng so‘nggi maslahatingiz bir soat davomida saqlanadi.\n{code} kodi bilan davom ettirishingiz mumkin.',
      recentLink: 'Yaqindagi maslahatni davom ettirish',
      restoredDraft: 'Siz yozayotgan maʼlumotlarni tikladik, shuning uchun davom ettirib maslahatni yuborishingiz mumkin.',
      languageHintEyebrow: 'Til bo‘yicha yordam',
      languageHintTitle: 'Siz {language} tilida yozishingiz mumkin.',
      languageHintBody: 'Biz {language} matnini avtomatik aniqlashga, shifokorlar uchun koreys tiliga tarjima qilishga va imkon bo‘lsa xuddi shu tilda tarjima qilingan javobni qaytarishga harakat qilamiz.',
      phoneConsentRequired: 'Javob haqida bildirishnoma olishni istasangiz, telefon raqamingizni kiriting.',
      phoneConsentMismatch: 'Biz javob bildirishnomasi uchun kontaktni faqat siz rozilik bergan holatda saqlaymiz.',
      submitError: 'Hozir maslahatni boshlay olmadik. Iltimos, birozdan keyin yana urinib ko‘ring.',
      ageLabel: 'Yosh yoki yosh oralig‘i',
      agePlaceholder: 'Masalan: 40 yoshlarda, 27 yosh',
      genderLabel: 'Jins',
      genderPlaceholder: 'Aytilmasin',
      chiefComplaintLabel: 'Asosiy alomat',
      chiefComplaintPlaceholder: 'Masalan: qorin og‘rigi, yo‘tal, isitma',
      onsetLabel: 'Qachondan boshlangan?',
      onsetPlaceholder: 'Masalan: bugun ertalabdan, 3 kun oldin',
      nrsLabel: 'Og‘riq yoki alomat darajasi',
      nrsUnknown: 'Bilmayman',
      symptomDetailLabel: 'Batafsilroq yozing',
      symptomDetailPlaceholder: 'Qaysi joyi qanday noqulay ekani va hozir sizni eng ko‘p nima tashvishga solayotganini yozing.',
      associatedLabel: 'Qo‘shimcha alomatlar',
      associatedPlaceholder: 'Masalan: qusish, isitma, ich ketishi, yo‘tal',
      historyLabel: 'Surunkali kasallik yoki dorilar',
      historyPlaceholder: 'Agar surunkali kasallik yoki ichayotgan dori bo‘lsa, yozing.',
      imageLabel: 'Rasm qo‘shish',
      imageDescription: 'Agar toshma, yara yoki dori qadoqlari rasmi bo‘lsa, bu holatingizni yaxshiroq tushunishimizga yordam beradi.\n3 tagacha rasm yuklashingiz mumkin, har biri 10MB gacha.',
      imageChooseLabel: 'Fayl tanlash',
      imageEmptyLabel: 'Hech qanday fayl tanlanmagan',
      imageSelectedLabel: '{count} ta fayl tanlandi',
      notificationTitle: 'Javob bildirishnomasi uchun telefon raqam qoldiring',
      notificationDescription: 'Ixtiyoriy. Biz bu kontaktni faqat javob haqida bildirishnoma olishga rozilik berganingizda ishlatamiz.',
      phoneLabel: 'Telefon raqami',
      phonePlaceholder: 'Masalan: +82 10-1234-5678',
      policyNote: 'Agar bu holat shoshilinchdek tuyulsa, avval tez yordam xizmatidan foydalaning. Happy Doctor shoshilinch tibbiy yordamning o‘rnini bosmaydi. Bu tibbiy yordamga yetib borish yanada qiyinlashishidan oldin yordam so‘rash kerak bo‘lgan odamlar uchun onlayn qo‘llab-quvvatlash xizmatidir.',
      submitLoading: 'Bodeum sizning maslahat maʼlumotingizni tartiblamoqda...',
      submitIdle: 'Veb orqali maslahatni boshlash',
      englishSupportNote: 'Bu sahifa siz tanlagan tilga tarjima qilingan. Keyingi javoblarda ayrim tibbiy nozik maʼnolarni qo‘shimcha aniqlashtirish talab qilinishi mumkin.',
    },
    genderOptionLabels: ['Ayol', 'Erkak', 'Boshqa', 'Aytilmasin'],
  }),
  ar: createBundle({
    page: {
      eyebrow: 'بدء الاستشارة مع Happy Doctor',
      title: 'ابدأ الاستشارة عبر الويب',
      description: 'اكتب المعلومات الضرورية فقط، وسنفتح استشارتك مع رابط الحالة ورمز المتابعة.',
      homeLabel: 'الصفحة الرئيسية الإنجليزية',
      statusLabel: 'تحقق من الحالة',
      heroEyebrow: 'بوابة طلب المساعدة',
      heroTitle: 'مكان يمكنك أن تشرح فيه أولاً\nعندما تبدو الرعاية الطبية بعيدة المنال',
      heroBody: 'هذه الصفحة هي نقطة دخول للدعم الطبي عبر الإنترنت للأشخاص الذين يحتاجون إلى شرح ما يحدث قبل أن يعرفوا أين يطلبون المساعدة.',
      infoTitle: 'أخبرنا',
      infoItems: [
        'ما هو العرض الأكثر إزعاجاً الآن',
        'متى بدأ',
        'هل لديك مرض مزمن أو أدوية تتناولها',
      ],
      supportEyebrow: 'كيف يعمل',
      supportTitle: 'اكتب بلغتك',
      supportItems: [
        'إذا بدت الأعراض طارئة، يرجى استخدام خدمات الطوارئ أولاً.',
        'يمكنك الكتابة باللغة التي اخترتها لهذه الصفحة.',
        'سنحاول ترجمة رسالتك تلقائياً لأطبائنا.',
      ],
    },
    form: {
      recentEyebrow: 'استشارة حديثة',
      recentBody: 'ستظل آخر استشارة لك متاحة لمدة ساعة واحدة.\nيمكنك المتابعة باستخدام الرمز {code}.',
      recentLink: 'متابعة الاستشارة الأخيرة',
      restoredDraft: 'أعدنا المعلومات التي كنت تكتبها حتى تتمكن من المتابعة وإرسال الاستشارة.',
      languageHintEyebrow: 'دعم اللغة',
      languageHintTitle: 'يمكنك الكتابة باللغة {language}.',
      languageHintBody: 'سنحاول اكتشاف النص المكتوب باللغة {language} تلقائياً، وترجمته إلى الكورية لأطبائنا، ثم إعادة الرد مترجماً باللغة نفسها عندما يكون ذلك ممكناً.',
      phoneConsentRequired: 'يرجى إدخال رقم هاتف إذا كنت تريد تلقي إشعارات عند وصول الرد.',
      phoneConsentMismatch: 'نحن نحفظ وسيلة الاتصال الخاصة بإشعارات الرد فقط إذا وافقت على تلقيها.',
      submitError: 'تعذر بدء الاستشارة الآن. يرجى المحاولة مرة أخرى بعد قليل.',
      ageLabel: 'العمر أو الفئة العمرية',
      agePlaceholder: 'مثال: في الأربعينيات، 27 سنة',
      genderLabel: 'الجنس',
      genderPlaceholder: 'أفضل عدم الإجابة',
      chiefComplaintLabel: 'العرض الرئيسي',
      chiefComplaintPlaceholder: 'مثال: ألم في المعدة، سعال، حمى',
      onsetLabel: 'متى بدأ؟',
      onsetPlaceholder: 'مثال: منذ هذا الصباح، منذ 3 أيام',
      nrsLabel: 'درجة الألم أو الأعراض',
      nrsUnknown: 'غير متأكد',
      symptomDetailLabel: 'أخبرنا بمزيد من التفاصيل',
      symptomDetailPlaceholder: 'يرجى وصف ما الذي يسبب لك الانزعاج وما الذي يقلقك أكثر الآن.',
      associatedLabel: 'أعراض أخرى مصاحبة',
      associatedPlaceholder: 'مثال: قيء، حمى، إسهال، سعال',
      historyLabel: 'أمراض مزمنة أو أدوية',
      historyPlaceholder: 'إذا كان لديك مرض مزمن أو أدوية تتناولها، فاكتب ذلك هنا.',
      imageLabel: 'إضافة صور',
      imageDescription: 'إذا كانت لديك صور لطفح جلدي أو جرح أو علبة دواء، فقد تساعدنا على فهم حالتك بشكل أفضل.\nيمكنك رفع حتى 3 صور، وبحد أقصى 10MB لكل صورة.',
      imageChooseLabel: 'اختر الملفات',
      imageEmptyLabel: 'لم يتم اختيار أي ملف',
      imageSelectedLabel: 'تم اختيار {count} ملف',
      notificationTitle: 'اترك رقم هاتف لتلقي إشعار عند الرد',
      notificationDescription: 'اختياري. نستخدم وسيلة الاتصال هذه فقط إذا وافقت على تلقي إشعار عند وصول الرد.',
      phoneLabel: 'رقم الهاتف',
      phonePlaceholder: 'مثال: +82 10-1234-5678',
      policyNote: 'إذا شعرت أن الحالة طارئة، يرجى استخدام خدمات الطوارئ أولاً. لا يحل Happy Doctor محل الرعاية الطارئة، بل هو خدمة دعم عبر الإنترنت للأشخاص الذين يحتاجون إلى طلب المساعدة قبل أن تصبح الرعاية الطبية أصعب منالاً.',
      submitLoading: 'يقوم Bodeum بترتيب محتوى استشارتك...',
      submitIdle: 'ابدأ الاستشارة عبر الويب',
      englishSupportNote: 'تمت ترجمة هذه الصفحة إلى اللغة التي اخترتها. قد تحتاج بعض التفاصيل الطبية الدقيقة إلى توضيح إضافي في الردود اللاحقة.',
    },
    genderOptionLabels: ['أنثى', 'ذكر', 'أخرى', 'أفضل عدم الإجابة'],
  }),
  fr: createBundle({
    page: {
      eyebrow: 'Début de consultation Happy Doctor',
      title: 'Commencer une consultation sur le web',
      description: 'Partagez uniquement les informations essentielles et nous ouvrirons votre consultation avec un lien de suivi et un code de recherche.',
      homeLabel: 'Page d’accueil anglaise',
      statusLabel: 'Vérifier l’état',
      heroEyebrow: 'Point d’entrée',
      heroTitle: 'Un endroit où expliquer d’abord\nquand l’accès aux soins semble trop lointain',
      heroBody: 'Cette page est une porte d’entrée vers un accompagnement médical en ligne pour les personnes qui doivent d’abord expliquer ce qui se passe avant de savoir où demander de l’aide.',
      infoTitle: 'Dites-nous',
      infoItems: [
        'quel est le symptôme le plus gênant en ce moment',
        'quand cela a commencé',
        'si vous avez une maladie chronique ou des médicaments en cours',
      ],
      supportEyebrow: 'Comment cela fonctionne',
      supportTitle: 'Écrivez dans votre langue',
      supportItems: [
        'Si vos symptômes semblent urgents, contactez d’abord les services d’urgence.',
        'Vous pouvez écrire dans la langue choisie pour cette page.',
        'Nous essaierons de traduire automatiquement votre message pour nos médecins.',
      ],
    },
    form: {
      recentEyebrow: 'Consultation récente',
      recentBody: 'Votre consultation la plus récente restera disponible pendant une heure.\nVous pouvez continuer avec le code {code}.',
      recentLink: 'Continuer la consultation récente',
      restoredDraft: 'Nous avons restauré ce que vous étiez en train de saisir afin que vous puissiez continuer et envoyer la consultation.',
      languageHintEyebrow: 'Prise en charge des langues',
      languageHintTitle: 'Vous pouvez écrire en {language}.',
      languageHintBody: 'Nous essaierons de détecter automatiquement le texte en {language}, de le traduire en coréen pour nos médecins, puis de renvoyer une réponse traduite dans la même langue si possible.',
      phoneConsentRequired: 'Veuillez saisir un numéro de téléphone si vous souhaitez recevoir une alerte lorsqu’une réponse arrive.',
      phoneConsentMismatch: 'Nous enregistrons ce contact uniquement si vous acceptez de recevoir une alerte de réponse.',
      submitError: 'Nous n’avons pas pu démarrer la consultation pour le moment. Veuillez réessayer dans quelques instants.',
      ageLabel: 'Âge ou tranche d’âge',
      agePlaceholder: 'Exemple : quarantaine, 27 ans',
      genderLabel: 'Genre',
      genderPlaceholder: 'Je préfère ne pas répondre',
      chiefComplaintLabel: 'Symptôme principal',
      chiefComplaintPlaceholder: 'Exemple : douleur au ventre, toux, fièvre',
      onsetLabel: 'Depuis quand ?',
      onsetPlaceholder: 'Exemple : depuis ce matin, depuis 3 jours',
      nrsLabel: 'Niveau de douleur ou des symptômes',
      nrsUnknown: 'Je ne sais pas',
      symptomDetailLabel: 'Dites-nous en plus',
      symptomDetailPlaceholder: 'Décrivez ce qui vous gêne et ce qui vous inquiète le plus en ce moment.',
      associatedLabel: 'Autres symptômes',
      associatedPlaceholder: 'Exemple : vomissements, fièvre, diarrhée, toux',
      historyLabel: 'Maladies chroniques ou médicaments',
      historyPlaceholder: 'Si vous avez une maladie chronique ou si vous prenez des médicaments, écrivez-le ici.',
      imageLabel: 'Ajouter des photos',
      imageDescription: 'Si vous avez des photos d’une éruption, d’une plaie ou d’une boîte de médicament, elles peuvent nous aider à mieux comprendre votre situation.\nVous pouvez envoyer jusqu’à 3 images, 10 MB maximum chacune.',
      imageChooseLabel: 'Choisir des fichiers',
      imageEmptyLabel: 'Aucun fichier sélectionné',
      imageSelectedLabel: '{count} fichiers sélectionnés',
      notificationTitle: 'Laisser un numéro pour les alertes de réponse',
      notificationDescription: 'Optionnel. Nous utilisons ce contact uniquement si vous acceptez de recevoir une alerte lorsqu’une réponse arrive.',
      phoneLabel: 'Numéro de téléphone',
      phonePlaceholder: 'Exemple : +82 10-1234-5678',
      policyNote: 'Si cela vous semble urgent, contactez d’abord les services d’urgence. Happy Doctor ne remplace pas les soins d’urgence. Il s’agit d’un service de soutien en ligne pour les personnes qui ont besoin de demander de l’aide avant que l’accès aux soins ne devienne encore plus difficile.',
      submitLoading: 'Bodeum organise votre consultation...',
      submitIdle: 'Commencer une consultation sur le web',
      englishSupportNote: 'Cette page est déjà traduite dans la langue que vous avez choisie. Certaines nuances médicales peuvent encore nécessiter une précision supplémentaire dans les réponses suivantes.',
    },
    genderOptionLabels: ['Femme', 'Homme', 'Autre', 'Je préfère ne pas répondre'],
  }),
  de: createBundle({
    page: {
      eyebrow: 'Start mit Happy Doctor',
      title: 'Beratung im Web starten',
      description: 'Teilen Sie nur die wichtigsten Informationen mit, und wir eröffnen Ihre Beratung mit einem Statuslink und einem Nachschlagecode.',
      homeLabel: 'Englische Startseite',
      statusLabel: 'Status prüfen',
      heroEyebrow: 'Erster Zugang',
      heroTitle: 'Ein Ort, an dem Sie zuerst erklären können,\nwenn medizinische Hilfe weit entfernt wirkt',
      heroBody: 'Diese Seite ist ein Einstieg in die medizinische Online-Unterstützung für Menschen, die zuerst erklären müssen, was passiert, bevor sie wissen, an wen sie sich wenden können.',
      infoTitle: 'Bitte teilen Sie uns mit',
      infoItems: [
        'welches Symptom Sie im Moment am meisten belastet',
        'wann es begonnen hat',
        'ob Sie chronische Erkrankungen haben oder Medikamente einnehmen',
      ],
      supportEyebrow: 'So funktioniert es',
      supportTitle: 'Schreiben Sie in Ihrer Sprache',
      supportItems: [
        'Wenn die Symptome dringend wirken, nutzen Sie bitte zuerst den Notdienst.',
        'Sie können in der Sprache schreiben, die Sie für diese Seite gewählt haben.',
        'Wir versuchen, Ihre Nachricht automatisch für unsere Ärztinnen und Ärzte zu übersetzen.',
      ],
    },
    form: {
      recentEyebrow: 'Letzte Beratung',
      recentBody: 'Ihre letzte Beratung bleibt eine Stunde lang verfügbar.\nMit dem Code {code} können Sie fortfahren.',
      recentLink: 'Letzte Beratung fortsetzen',
      restoredDraft: 'Wir haben Ihre Eingaben wiederhergestellt, damit Sie fortfahren und die Beratung absenden können.',
      languageHintEyebrow: 'Sprachunterstützung',
      languageHintTitle: 'Sie können auf {language} schreiben.',
      languageHintBody: 'Wir versuchen, Texte auf {language} automatisch zu erkennen, für unsere Ärztinnen und Ärzte ins Koreanische zu übersetzen und wenn möglich in derselben Sprache zurückzusenden.',
      phoneConsentRequired: 'Bitte geben Sie eine Telefonnummer ein, wenn Sie eine Antwortbenachrichtigung erhalten möchten.',
      phoneConsentMismatch: 'Wir speichern den Kontakt für Antwortbenachrichtigungen nur, wenn Sie dem Erhalt zustimmen.',
      submitError: 'Die Beratung konnte im Moment nicht gestartet werden. Bitte versuchen Sie es in Kürze erneut.',
      ageLabel: 'Alter oder Altersgruppe',
      agePlaceholder: 'Beispiel: in den 40ern, 27 Jahre alt',
      genderLabel: 'Geschlecht',
      genderPlaceholder: 'Ich möchte das nicht angeben',
      chiefComplaintLabel: 'Hauptsymptom',
      chiefComplaintPlaceholder: 'Beispiel: Bauchschmerzen, Husten, Fieber',
      onsetLabel: 'Seit wann besteht das?',
      onsetPlaceholder: 'Beispiel: seit heute Morgen, seit 3 Tagen',
      nrsLabel: 'Schmerz- oder Symptomstärke',
      nrsUnknown: 'Nicht sicher',
      symptomDetailLabel: 'Bitte erzählen Sie mehr',
      symptomDetailPlaceholder: 'Beschreiben Sie, was Ihnen Beschwerden macht und worüber Sie sich im Moment am meisten Sorgen machen.',
      associatedLabel: 'Weitere Symptome',
      associatedPlaceholder: 'Beispiel: Erbrechen, Fieber, Durchfall, Husten',
      historyLabel: 'Chronische Erkrankungen oder Medikamente',
      historyPlaceholder: 'Bitte schreiben Sie auf, wenn Sie eine chronische Erkrankung haben oder Medikamente einnehmen.',
      imageLabel: 'Fotos hinzufügen',
      imageDescription: 'Wenn Sie Fotos von einem Ausschlag, einer Wunde oder einer Medikamentenpackung haben, helfen sie uns, Ihre Situation besser zu verstehen.\nSie können bis zu 3 Bilder hochladen, jeweils bis zu 10 MB.',
      imageChooseLabel: 'Dateien auswählen',
      imageEmptyLabel: 'Keine Datei ausgewählt',
      imageSelectedLabel: '{count} Dateien ausgewählt',
      notificationTitle: 'Telefonnummer für Antwortbenachrichtigungen hinterlassen',
      notificationDescription: 'Optional. Wir nutzen diesen Kontakt nur, wenn Sie einer Benachrichtigung bei Antwort zustimmen.',
      phoneLabel: 'Telefonnummer',
      phonePlaceholder: 'Beispiel: +82 10-1234-5678',
      policyNote: 'Wenn es sich dringend anfühlt, nutzen Sie bitte zuerst den Notdienst. Happy Doctor ersetzt keine Notfallversorgung. Es ist ein Online-Unterstützungsdienst für Menschen, die Hilfe benötigen, bevor medizinische Versorgung noch schwerer erreichbar wird.',
      submitLoading: 'Bodeum ordnet gerade Ihre Beratungsangaben...',
      submitIdle: 'Beratung im Web starten',
      englishSupportNote: 'Diese Seite wurde bereits in die von Ihnen gewählte Sprache übersetzt. Einige medizinische Feinheiten müssen in späteren Antworten eventuell noch genauer geklärt werden.',
    },
    genderOptionLabels: ['Weiblich', 'Männlich', 'Andere', 'Ich möchte das nicht angeben'],
  }),
  pt: createBundle({
    page: {
      eyebrow: 'Início com Happy Doctor',
      title: 'Começar a consulta na web',
      description: 'Compartilhe apenas as informações essenciais e abriremos sua consulta com um link de status e um código de consulta.',
      homeLabel: 'Página inicial em inglês',
      statusLabel: 'Verificar status',
      heroEyebrow: 'Porta de entrada',
      heroTitle: 'Um lugar para explicar primeiro\nquando o acesso à saúde parece distante',
      heroBody: 'Esta página é uma porta de entrada para apoio médico online para pessoas que precisam explicar o que está acontecendo antes de saber onde pedir ajuda.',
      infoTitle: 'Conte para nós',
      infoItems: [
        'qual é o sintoma que mais incomoda agora',
        'quando começou',
        'se você tem doença crônica ou toma algum medicamento',
      ],
      supportEyebrow: 'Como funciona',
      supportTitle: 'Escreva no seu idioma',
      supportItems: [
        'Se os sintomas parecerem urgentes, procure primeiro o serviço de emergência.',
        'Você pode escrever no idioma escolhido para esta página.',
        'Tentaremos traduzir automaticamente sua mensagem para nossos médicos.',
      ],
    },
    form: {
      recentEyebrow: 'Consulta recente',
      recentBody: 'Sua consulta mais recente ficará disponível por uma hora.\nVocê pode continuar com o código {code}.',
      recentLink: 'Continuar consulta recente',
      restoredDraft: 'Recuperamos o que você estava digitando para que possa continuar e enviar a consulta.',
      languageHintEyebrow: 'Suporte de idioma',
      languageHintTitle: 'Você pode escrever em {language}.',
      languageHintBody: 'Tentaremos detectar automaticamente o texto em {language}, traduzi-lo para o coreano para nossos médicos e, quando possível, devolver uma resposta traduzida no mesmo idioma.',
      phoneConsentRequired: 'Digite um número de telefone se quiser receber alerta quando houver resposta.',
      phoneConsentMismatch: 'Só salvamos um contato para alerta de resposta quando você concorda em recebê-lo.',
      submitError: 'Não foi possível iniciar a consulta agora. Tente novamente em instantes.',
      ageLabel: 'Idade ou faixa etária',
      agePlaceholder: 'Exemplo: na faixa dos 40, 27 anos',
      genderLabel: 'Gênero',
      genderPlaceholder: 'Prefiro não informar',
      chiefComplaintLabel: 'Sintoma principal',
      chiefComplaintPlaceholder: 'Exemplo: dor de estômago, tosse, febre',
      onsetLabel: 'Quando começou?',
      onsetPlaceholder: 'Exemplo: hoje de manhã, há 3 dias',
      nrsLabel: 'Nível de dor ou dos sintomas',
      nrsUnknown: 'Não sei',
      symptomDetailLabel: 'Conte mais detalhes',
      symptomDetailPlaceholder: 'Descreva o que está incomodando e qual é a sua maior preocupação neste momento.',
      associatedLabel: 'Outros sintomas',
      associatedPlaceholder: 'Exemplo: vômito, febre, diarreia, tosse',
      historyLabel: 'Doenças crônicas ou medicamentos',
      historyPlaceholder: 'Se você tem alguma doença crônica ou usa medicamentos, escreva aqui.',
      imageLabel: 'Adicionar fotos',
      imageDescription: 'Se você tiver fotos de manchas, feridas ou da embalagem de remédios, isso pode nos ajudar a entender melhor sua situação.\nVocê pode enviar até 3 imagens, com até 10 MB cada.',
      imageChooseLabel: 'Escolher arquivos',
      imageEmptyLabel: 'Nenhum arquivo selecionado',
      imageSelectedLabel: '{count} arquivos selecionados',
      notificationTitle: 'Deixe um número para alertas de resposta',
      notificationDescription: 'Opcional. Só usamos esse contato se você concordar em receber um alerta quando houver resposta.',
      phoneLabel: 'Número de telefone',
      phonePlaceholder: 'Exemplo: +82 10-1234-5678',
      policyNote: 'Se isso parecer urgente, procure primeiro o serviço de emergência. Happy Doctor não substitui o atendimento de urgência. É um serviço de apoio online para pessoas que precisam pedir ajuda antes que o acesso à saúde fique ainda mais difícil.',
      submitLoading: 'Bodeum está organizando sua consulta...',
      submitIdle: 'Começar a consulta na web',
      englishSupportNote: 'Esta página já foi traduzida para o idioma que você escolheu. Alguns detalhes médicos podem precisar de esclarecimentos adicionais nas próximas respostas.',
    },
    genderOptionLabels: ['Feminino', 'Masculino', 'Outro', 'Prefiro não informar'],
  }),
  it: createBundle({
    page: {
      eyebrow: 'Inizio con Happy Doctor',
      title: 'Avvia una consulenza sul web',
      description: 'Condividi solo le informazioni essenziali e apriremo la tua consulenza con un link di stato e un codice di verifica.',
      homeLabel: 'Homepage in inglese',
      statusLabel: 'Controlla lo stato',
      heroEyebrow: 'Punto di accesso',
      heroTitle: 'Un luogo in cui spiegare prima\nquando l’assistenza sanitaria sembra lontana',
      heroBody: 'Questa pagina è un punto di ingresso per il supporto medico online per le persone che hanno bisogno di spiegare cosa sta succedendo prima di sapere a chi chiedere aiuto.',
      infoTitle: 'Dicci',
      infoItems: [
        'qual è il sintomo che ti dà più fastidio in questo momento',
        'quando è iniziato',
        'se hai malattie croniche o farmaci che stai assumendo',
      ],
      supportEyebrow: 'Come funziona',
      supportTitle: 'Scrivi nella tua lingua',
      supportItems: [
        'Se i sintomi sembrano urgenti, contatta prima i servizi di emergenza.',
        'Puoi scrivere nella lingua scelta per questa pagina.',
        'Cercheremo di tradurre automaticamente il tuo messaggio per i nostri medici.',
      ],
    },
    form: {
      recentEyebrow: 'Consulenza recente',
      recentBody: 'La tua consulenza più recente resterà disponibile per un’ora.\nPuoi continuare con il codice {code}.',
      recentLink: 'Continua la consulenza recente',
      restoredDraft: 'Abbiamo ripristinato ciò che stavi scrivendo così puoi continuare e inviare la consulenza.',
      languageHintEyebrow: 'Supporto lingua',
      languageHintTitle: 'Puoi scrivere in {language}.',
      languageHintBody: 'Cercheremo di rilevare automaticamente il testo in {language}, tradurlo in coreano per i nostri medici e restituire una risposta tradotta nella stessa lingua quando possibile.',
      phoneConsentRequired: 'Inserisci un numero di telefono se vuoi ricevere un avviso quando arriva una risposta.',
      phoneConsentMismatch: 'Salviamo il contatto per gli avvisi solo se accetti di riceverli.',
      submitError: 'Non siamo riusciti ad avviare la consulenza in questo momento. Riprova tra poco.',
      ageLabel: 'Età o fascia d’età',
      agePlaceholder: 'Esempio: sui 40 anni, 27 anni',
      genderLabel: 'Genere',
      genderPlaceholder: 'Preferisco non dirlo',
      chiefComplaintLabel: 'Sintomo principale',
      chiefComplaintPlaceholder: 'Esempio: mal di pancia, tosse, febbre',
      onsetLabel: 'Quando è iniziato?',
      onsetPlaceholder: 'Esempio: questa mattina, 3 giorni fa',
      nrsLabel: 'Livello di dolore o dei sintomi',
      nrsUnknown: 'Non lo so',
      symptomDetailLabel: 'Raccontaci qualcosa in più',
      symptomDetailPlaceholder: 'Descrivi cosa ti dà fastidio e qual è la tua preoccupazione principale in questo momento.',
      associatedLabel: 'Altri sintomi',
      associatedPlaceholder: 'Esempio: vomito, febbre, diarrea, tosse',
      historyLabel: 'Malattie croniche o farmaci',
      historyPlaceholder: 'Se hai malattie croniche o farmaci che stai assumendo, scrivilo qui.',
      imageLabel: 'Aggiungi foto',
      imageDescription: 'Se hai foto di un’eruzione, una ferita o una confezione di farmaci, possono aiutarci a capire meglio la tua situazione.\nPuoi caricare fino a 3 immagini, massimo 10 MB ciascuna.',
      imageChooseLabel: 'Scegli file',
      imageEmptyLabel: 'Nessun file selezionato',
      imageSelectedLabel: '{count} file selezionati',
      notificationTitle: 'Lascia un numero per gli avvisi di risposta',
      notificationDescription: 'Facoltativo. Usiamo questo contatto solo se accetti di ricevere un avviso quando arriva una risposta.',
      phoneLabel: 'Numero di telefono',
      phonePlaceholder: 'Esempio: +82 10-1234-5678',
      policyNote: 'Se la situazione sembra urgente, contatta prima i servizi di emergenza. Happy Doctor non sostituisce l’assistenza d’urgenza. È un servizio di supporto online per le persone che hanno bisogno di chiedere aiuto prima che l’accesso alle cure diventi ancora più difficile.',
      submitLoading: 'Bodeum sta organizzando la tua consulenza...',
      submitIdle: 'Avvia una consulenza sul web',
      englishSupportNote: 'Questa pagina è già tradotta nella lingua che hai scelto. Alcune sfumature mediche potrebbero comunque richiedere ulteriori chiarimenti nelle risposte successive.',
    },
    genderOptionLabels: ['Femmina', 'Maschio', 'Altro', 'Preferisco non dirlo'],
  }),
  hi: createBundle({
    page: {
      eyebrow: 'Happy Doctor शुरुआत',
      title: 'वेब पर परामर्श शुरू करें',
      description: 'सिर्फ आवश्यक जानकारी लिखें। हम आपकी परामर्श प्रविष्टि को स्थिति लिंक और जाँच कोड के साथ शुरू करेंगे।',
      homeLabel: 'अंग्रेज़ी होमपेज',
      statusLabel: 'स्थिति देखें',
      heroEyebrow: 'मदद की शुरुआत',
      heroTitle: 'एक ऐसी जगह जहाँ आप पहले अपनी बात बता सकें\nजब चिकित्सा सहायता बहुत दूर लगती हो',
      heroBody: 'यह पृष्ठ उन लोगों के लिए ऑनलाइन चिकित्सकीय सहायता का प्रवेश बिंदु है जिन्हें यह समझने से पहले कि मदद कहाँ से माँगनी है, अपनी स्थिति समझानी होती है।',
      infoTitle: 'हमें बताइए',
      infoItems: [
        'अभी सबसे ज़्यादा परेशान करने वाला लक्षण क्या है',
        'यह कब से शुरू हुआ',
        'क्या कोई पुरानी बीमारी है या कोई दवा चल रही है',
      ],
      supportEyebrow: 'यह कैसे काम करता है',
      supportTitle: 'अपनी भाषा में लिखें',
      supportItems: [
        'यदि लक्षण आपातकाल जैसे लगें, तो पहले आपातकालीन सेवा लें।',
        'आप इस पृष्ठ के लिए चुनी गई भाषा में लिख सकते हैं।',
        'हम आपके संदेश का चिकित्सकों के लिए स्वचालित अनुवाद करने की कोशिश करेंगे।',
      ],
    },
    form: {
      recentEyebrow: 'हाल की परामर्श',
      recentBody: 'आपकी सबसे हाल की परामर्श एक घंटे तक उपलब्ध रहेगी।\nआप {code} कोड के साथ आगे बढ़ सकते हैं।',
      recentLink: 'हाल की परामर्श जारी रखें',
      restoredDraft: 'आप जो लिख रहे थे, उसे हमने वापस रख दिया है ताकि आप आगे बढ़कर परामर्श भेज सकें।',
      languageHintEyebrow: 'भाषा सहायता',
      languageHintTitle: 'आप {language} में लिख सकते हैं।',
      languageHintBody: 'हम {language} इनपुट को अपने आप पहचानने, डॉक्टरों के लिए उसे कोरियाई में अनुवाद करने, और संभव होने पर उसी भाषा में अनूदित उत्तर लौटाने की कोशिश करेंगे।',
      phoneConsentRequired: 'यदि आप उत्तर का अलर्ट पाना चाहते हैं, तो कृपया फोन नंबर दर्ज करें।',
      phoneConsentMismatch: 'हम उत्तर अलर्ट के लिए संपर्क जानकारी केवल तभी सहेजते हैं जब आप उसे प्राप्त करने की सहमति देते हैं।',
      submitError: 'अभी परामर्श शुरू नहीं किया जा सका। कृपया थोड़ी देर बाद फिर प्रयास करें।',
      ageLabel: 'उम्र या आयु समूह',
      agePlaceholder: 'उदाहरण: 40 के आसपास, 27 वर्ष',
      genderLabel: 'लिंग',
      genderPlaceholder: 'बताना नहीं चाहते',
      chiefComplaintLabel: 'मुख्य लक्षण',
      chiefComplaintPlaceholder: 'उदाहरण: पेट दर्द, खाँसी, बुखार',
      onsetLabel: 'यह कब शुरू हुआ?',
      onsetPlaceholder: 'उदाहरण: आज सुबह से, 3 दिन पहले से',
      nrsLabel: 'दर्द या लक्षण का स्तर',
      nrsUnknown: 'पता नहीं',
      symptomDetailLabel: 'थोड़ा और विस्तार से लिखें',
      symptomDetailPlaceholder: 'कहाँ और किस तरह तकलीफ़ है, और इस समय आपको सबसे ज़्यादा किस बात की चिंता है, कृपया लिखें।',
      associatedLabel: 'साथ में होने वाले अन्य लक्षण',
      associatedPlaceholder: 'उदाहरण: उल्टी, बुखार, दस्त, खाँसी',
      historyLabel: 'पुरानी बीमारी या चल रही दवाएँ',
      historyPlaceholder: 'यदि कोई पुरानी बीमारी है या आप कोई दवा ले रहे हैं, तो कृपया लिखें।',
      imageLabel: 'तस्वीर जोड़ें',
      imageDescription: 'यदि आपके पास दाने, घाव या दवा के पैकेट जैसी तस्वीरें हैं, तो वे हमें आपकी स्थिति बेहतर समझने में मदद कर सकती हैं।\nआप अधिकतम 3 तस्वीरें अपलोड कर सकते हैं, हर तस्वीर 10MB तक।',
      imageChooseLabel: 'फ़ाइल चुनें',
      imageEmptyLabel: 'कोई फ़ाइल चुनी नहीं गई',
      imageSelectedLabel: '{count} फ़ाइलें चुनी गईं',
      notificationTitle: 'उत्तर अलर्ट के लिए फोन नंबर छोड़ें',
      notificationDescription: 'वैकल्पिक। हम इस संपर्क का उपयोग केवल तभी करेंगे जब आप उत्तर आने पर अलर्ट लेने की सहमति दें।',
      phoneLabel: 'फोन नंबर',
      phonePlaceholder: 'उदाहरण: +82 10-1234-5678',
      policyNote: 'यदि यह स्थिति आपातकाल जैसी लगे, तो पहले आपातकालीन सेवा लें। Happy Doctor आपातकालीन चिकित्सा का विकल्प नहीं है। यह उन लोगों के लिए ऑनलाइन सहायता सेवा है जिन्हें चिकित्सा सहायता तक पहुँचना और कठिन होने से पहले मदद माँगनी होती है।',
      submitLoading: 'Bodeum आपकी परामर्श जानकारी व्यवस्थित कर रहा है...',
      submitIdle: 'वेब पर परामर्श शुरू करें',
      englishSupportNote: 'यह पृष्ठ आपकी चुनी हुई भाषा में अनूदित है। कुछ चिकित्सकीय सूक्ष्मताओं के लिए आगे आने वाले उत्तरों में अतिरिक्त स्पष्टता की ज़रूरत पड़ सकती है।',
    },
    genderOptionLabels: ['महिला', 'पुरुष', 'अन्य', 'बताना नहीं चाहते'],
  }),
  tr: createBundle({
    page: {
      eyebrow: 'Happy Doctor başlangıcı',
      title: 'Web üzerinden danışma başlatın',
      description: 'Yalnızca gerekli bilgileri paylaşın; size durum bağlantısı ve sorgu kodu ile birlikte danışma kaydı açalım.',
      homeLabel: 'İngilizce ana sayfa',
      statusLabel: 'Durumu kontrol et',
      heroEyebrow: 'Yardım kapısı',
      heroTitle: 'Sağlık hizmeti çok uzakta hissettirdiğinde\nönce durumu anlatabileceğiniz bir yer',
      heroBody: 'Bu sayfa, nereden yardım isteyeceğini bilmeden önce yaşadığını anlatmak isteyen kişiler için çevrim içi tıbbi destek giriş noktasıdır.',
      infoTitle: 'Bize anlatın',
      infoItems: [
        'şu anda en çok rahatsız eden belirti nedir',
        'ne zamandır var',
        'kronik hastalık ya da kullandığınız ilaç olup olmadığı',
      ],
      supportEyebrow: 'Nasıl işler',
      supportTitle: 'Kendi dilinizde yazın',
      supportItems: [
        'Belirtiler acil görünüyorsa önce acil servise başvurun.',
        'Bu sayfa için seçtiğiniz dilde yazabilirsiniz.',
        'Mesajınızı doktorlarımız için otomatik çevirmeye çalışacağız.',
      ],
    },
    form: {
      recentEyebrow: 'Son danışma',
      recentBody: 'En son danışmanız bir saat boyunca kullanılabilir durumda kalır.\n{code} kodu ile devam edebilirsiniz.',
      recentLink: 'Son danışmaya devam et',
      restoredDraft: 'Yazmakta olduğunuz bilgileri geri yükledik, böylece devam edip danışmayı gönderebilirsiniz.',
      languageHintEyebrow: 'Dil desteği',
      languageHintTitle: '{language} dilinde yazabilirsiniz.',
      languageHintBody: '{language} metnini otomatik olarak algılamaya, doktorlarımız için Koreceye çevirmeye ve mümkünse yanıtı aynı dilde geri göndermeye çalışacağız.',
      phoneConsentRequired: 'Yanıt bildirimi almak istiyorsanız lütfen telefon numaranızı girin.',
      phoneConsentMismatch: 'Yanıt bildirimi için iletişim bilgisini yalnızca bunu almayı kabul ettiğinizde saklarız.',
      submitError: 'Danışma şu anda başlatılamadı. Lütfen biraz sonra tekrar deneyin.',
      ageLabel: 'Yaş veya yaş aralığı',
      agePlaceholder: 'Örnek: 40’lı yaşlar, 27 yaş',
      genderLabel: 'Cinsiyet',
      genderPlaceholder: 'Belirtmek istemiyorum',
      chiefComplaintLabel: 'Ana belirti',
      chiefComplaintPlaceholder: 'Örnek: karın ağrısı, öksürük, ateş',
      onsetLabel: 'Ne zamandır var?',
      onsetPlaceholder: 'Örnek: bu sabah, 3 gün önce',
      nrsLabel: 'Ağrı veya belirti düzeyi',
      nrsUnknown: 'Bilmiyorum',
      symptomDetailLabel: 'Biraz daha anlatın',
      symptomDetailPlaceholder: 'Nerenin nasıl rahatsız olduğunu ve şu anda sizi en çok neyin kaygılandırdığını yazın.',
      associatedLabel: 'Eşlik eden diğer belirtiler',
      associatedPlaceholder: 'Örnek: kusma, ateş, ishal, öksürük',
      historyLabel: 'Kronik hastalık veya kullanılan ilaçlar',
      historyPlaceholder: 'Kronik bir hastalığınız veya kullandığınız ilaç varsa lütfen yazın.',
      imageLabel: 'Fotoğraf ekle',
      imageDescription: 'Döküntü, yara veya ilaç paketi gibi fotoğraflarınız varsa, durumunuzu daha iyi anlamamıza yardımcı olabilir.\nHer biri en fazla 10MB olmak üzere en fazla 3 görsel yükleyebilirsiniz.',
      imageChooseLabel: 'Dosya seç',
      imageEmptyLabel: 'Dosya seçilmedi',
      imageSelectedLabel: '{count} dosya seçildi',
      notificationTitle: 'Yanıt bildirimi için telefon numarası bırakın',
      notificationDescription: 'İsteğe bağlıdır. Bu iletişim bilgisini yalnızca yanıt bildirimi almayı kabul ettiğinizde kullanırız.',
      phoneLabel: 'Telefon numarası',
      phonePlaceholder: 'Örnek: +82 10-1234-5678',
      policyNote: 'Durum acil görünüyorsa önce acil servise başvurun. Happy Doctor acil bakımın yerine geçmez. Sağlık hizmetine ulaşım daha da zorlaşmadan önce yardım istemesi gereken kişiler için çevrim içi bir destek hizmetidir.',
      submitLoading: 'Bodeum danışma bilgilerinizi düzenliyor...',
      submitIdle: 'Web üzerinden danışma başlat',
      englishSupportNote: 'Bu sayfa seçtiğiniz dile çevrilmiştir. Bazı tıbbi ayrıntılar sonraki yanıtlarda ek açıklama gerektirebilir.',
    },
    genderOptionLabels: ['Kadın', 'Erkek', 'Diğer', 'Belirtmek istemiyorum'],
  }),
}
